import { q } from "../question-factory";
import type { Question } from "../schema";

export const FOUNDATION_QUESTIONS: Question[] = [
  q({
    id: "FND-D0-O1-CERT-Q001",
    objectiveId: "FND-D0-O1",
    conceptIds: ["FND-D0-O1-CERT", "FND-D0-O1-CORES"],
    stem: "A learner wants the current CompTIA A+ credential. Which statement is accurate?",
    choices: [
      { id: "a", text: "Passing Core 1 (220-1201) alone is enough if the employer only supports hardware.", rationale: "A+ requires both Core 1 and Core 2 from the same version." },
      { id: "b", text: "They must pass Core 1 (220-1201) and Core 2 (220-1202) from the same version.", rationale: "Correct. V15 is a pair; mixing versions is not allowed." },
      { id: "c", text: "They can mix a retired 220-1101 with a 220-1202 because the domains look similar.", rationale: "CompTIA does not allow mixing versions." },
      { id: "d", text: "Core 2 is optional if they skip the security domain in this academy.", rationale: "Security is 28% of Core 2. The credential still requires the exam." },
    ],
    correct: "b",
    explanation: "A+ V15 is two exams: 220-1201 and 220-1202. Both must come from the same version.",
    sourceBasis: "comptia-a-v15",
  }),
  q({
    id: "FND-D0-O1-CERT-Q002",
    objectiveId: "FND-D0-O1",
    conceptIds: ["FND-D0-O1-CERT"],
    difficulty: "intro",
    stem: "Which pair is the current A+ V15 series?",
    choices: [
      { id: "a", text: "220-1001 and 220-1002", rationale: "Those are retired older codes." },
      { id: "b", text: "220-1101 and 220-1102", rationale: "V14, retired in English in 2025." },
      { id: "c", text: "220-1201 and 220-1202", rationale: "Correct V15 codes." },
      { id: "d", text: "N10-008 and SY0-701", rationale: "Those are Network+ and Security+." },
    ],
    correct: "c",
    explanation: "V15 uses 220-1201 (Core 1) and 220-1202 (Core 2).",
    sourceBasis: "comptia-a-v15",
  }),
  q({
    id: "FND-D0-O1-CORES-Q001",
    objectiveId: "FND-D0-O1",
    conceptIds: ["FND-D0-O1-CORES"],
    stem: "Which topic belongs on Core 2 rather than Core 1?",
    choices: [
      { id: "a", text: "RAID 10 capacity and a failed disk in an array", rationale: "Storage/RAID is Core 1 hardware and troubleshooting." },
      { id: "b", text: "T568B wire order", rationale: "Cabling is Core 1." },
      { id: "c", text: "NTFS vs share permissions and a malware-removal order", rationale: "OS security and malware process are Core 2." },
      { id: "d", text: "PoE injectors versus PoE switches", rationale: "Network hardware is Core 1." },
    ],
    correct: "c",
    explanation: "Core 2 owns operating systems, security, software troubleshooting, and operational procedures.",
    sourceBasis: "c2-obj-3.0",
  }),
  q({
    id: "FND-D0-O1-SCORES-Q001",
    objectiveId: "FND-D0-O1",
    conceptIds: ["FND-D0-O1-SCORES"],
    stem: "This academy shows Internal Readiness 80% after a Core 1 mock. What is the honest interpretation?",
    choices: [
      { id: "a", text: "CompTIA will report 800 on the 100–900 scale.", rationale: "There is no legitimate conversion from this app's percentage to CompTIA's scaled score." },
      { id: "b", text: "The learner has already met the official 675 passing score.", rationale: "675 is CompTIA's scaled score, not 67.5% and not this app's readiness." },
      { id: "c", text: "It is this course's own mastery estimate and is not CompTIA's scaled score.", rationale: "Correct. Internal Readiness is labeled that way on purpose." },
      { id: "d", text: "80% guarantees a pass because official exams use simple percent scoring.", rationale: "Official scoring is scaled 100–900 and this app cannot guarantee a pass." },
    ],
    correct: "c",
    explanation: "Never map Internal Readiness onto CompTIA's 100–900 scale or treat it as a guarantee.",
    sourceBasis: "comptia-a-v15",
  }),
  q({
    id: "FND-D0-O2-GATES-Q001",
    objectiveId: "FND-D0-O2",
    conceptIds: ["FND-D0-O2-GATES"],
    stem: "A learner scores 12/15 on a domain mastery quiz. What happens?",
    choices: [
      { id: "a", text: "The next domain unlocks because 80% is a typical school pass.", rationale: "This academy requires 100% on domain mastery quizzes." },
      { id: "b", text: "The three missed concepts are reviewed, queued, and a new attempt is required. Prior scores remain.", rationale: "Correct. 100% gate, remediation, new items, history kept." },
      { id: "c", text: "The previous score is deleted so they are not discouraged.", rationale: "Prior scores are never deleted." },
      { id: "d", text: "They skip to the Core mock because the diagnostic already showed strength there.", rationale: "Diagnostics do not skip required curriculum." },
    ],
    correct: "b",
    explanation: "Domain quizzes are 100% gates. Misses go to review and a fresh attempt; history stays.",
    sourceBasis: "comptia-a-v15",
  }),
  q({
    id: "FND-D0-O2-GATES-Q002",
    objectiveId: "FND-D0-O2",
    conceptIds: ["FND-D0-O2-CYCLE", "FND-D0-O2-GATES"],
    stem: "What is required before the next instructional block unlocks in a lesson?",
    choices: [
      { id: "a", text: "Watching a generated video to the last second.", rationale: "Videos are optional aids. Checks are mandatory and multiple-choice." },
      { id: "b", text: "A correct required knowledge-check answer (after remediation if needed).", rationale: "Correct. Wrong answers teach, then you retry until correct." },
      { id: "c", text: "Typing a free-text summary of the paragraph.", rationale: "Required checks are never free-text in this academy." },
      { id: "d", text: "Scoring 70% on an optional survey.", rationale: "There is no 70% skip hatch on blocks." },
    ],
    correct: "b",
    explanation: "Each meaningful reading block is followed by a required MC check you must get right.",
    sourceBasis: "comptia-a-v15",
  }),
  q({
    id: "FND-D0-O2-REVIEW-Q001",
    objectiveId: "FND-D0-O2",
    conceptIds: ["FND-D0-O2-REVIEW"],
    stem: "Why does the Review Queue mix RAID items with backup and SATA questions days later?",
    choices: [
      { id: "a", text: "The database is randomizing bugs.", rationale: "Interleaving is deliberate so you distinguish related ideas." },
      { id: "b", text: "Interleaving forces you to distinguish related concepts instead of memorizing a streak.", rationale: "Correct." },
      { id: "c", text: "CompTIA requires RAID questions to appear in groups of ten.", rationale: "No such rule. Grouping would make practice easier than the exam." },
      { id: "d", text: "Cloud sync cannot store one topic at a time.", rationale: "Storage has nothing to do with it." },
    ],
    correct: "b",
    explanation: "Spaced, interleaved review is how retention is tested, not topic-blocked drilling.",
    sourceBasis: "comptia-a-v15",
  }),
  q({
    id: "FND-D0-O3-STEMS-Q001",
    objectiveId: "FND-D0-O3",
    conceptIds: ["FND-D0-O3-STEMS"],
    stem: "A printer is faded. Which exam stem is asking about sequence rather than the single best fix?",
    choices: [
      { id: "a", text: "Which action is BEST?", rationale: "BEST is about quality/completeness of the action." },
      { id: "b", text: "Which action should the technician do FIRST?", rationale: "FIRST is sequence — often identify/isolate before replacing parts." },
      { id: "c", text: "Which printer type uses a fuser?", rationale: "That is a knowledge item, not sequence." },
      { id: "d", text: "Which cable carries analog video?", rationale: "Irrelevant hardware trivia." },
    ],
    correct: "b",
    explanation: "FIRST/NEXT encode order. BEST encodes quality among workable options.",
    sourceBasis: "c1-obj-3.0",
  }),
  q({
    id: "FND-D0-O3-STEMS-Q002",
    objectiveId: "FND-D0-O3",
    conceptIds: ["FND-D0-O3-STEMS"],
    difficulty: "exam",
    type: "scenario",
    scenario: "A user says the internet is down. You can ping 1.1.1.1 but not the hostname intranet.company.local.",
    stem: "If the item asks what the technician should do NEXT and you already confirmed the NIC has a DHCP address and gateway, which direction is MOST appropriate?",
    choices: [
      { id: "a", text: "Replace the NIC because ping proves nothing.", rationale: "Ping to an IP already shows a working path off the NIC." },
      { id: "b", text: "Investigate name resolution (DNS) rather than physical cabling.", rationale: "IP works, name fails: that pattern points at DNS, not Layer 1." },
      { id: "c", text: "Reimage Windows because name resolution is an OS corruption symptom.", rationale: "Way too aggressive for a DNS pattern." },
      { id: "d", text: "Install a new switch to reduce collisions.", rationale: "Does not match the evidence." },
    ],
    correct: "b",
    explanation: "NEXT depends on evidence already gathered. Successful IP ping plus failed name lookup is DNS-shaped.",
    sourceBasis: "c1-obj-3.0",
  }),
  q({
    id: "FND-D0-O3-PBQ-Q001",
    objectiveId: "FND-D0-O3",
    conceptIds: ["FND-D0-O3-PBQ"],
    stem: "How does this academy treat performance-based practice?",
    choices: [
      { id: "a", text: "It clones live CompTIA PBQs collected from exam dumps.", rationale: "Brain dumps are forbidden and would get a certification revoked." },
      { id: "b", text: "It uses original labs that train the same skills (RAID, router, CLI, tickets) and then explains the solution.", rationale: "Correct." },
      { id: "c", text: "It skips PBQs because they cannot be simulated in a browser.", rationale: "The course is built around browser labs." },
      { id: "d", text: "It requires free-text essays instead of labs.", rationale: "Required checks are MCQ; labs are interactive, not essays." },
    ],
    correct: "b",
    explanation: "Original PBQ-style labs, never dumps, with explanations after completion.",
    sourceBasis: "comptia-a-v15",
  }),
  q({
    id: "FND-D0-O4-TS-METHOD-Q001",
    objectiveId: "FND-D0-O4",
    conceptIds: ["FND-D0-O4-TS-METHOD"],
    stem: "A PC is dead at the desk. Which action best matches 'identify the problem' rather than a random theory?",
    choices: [
      { id: "a", text: "Immediately replace the PSU because last week's ticket was a PSU.", rationale: "That is implementing a theory before identifying this problem." },
      { id: "b", text: "Ask what changed, whether other devices work, and whether the outlet is live, then reproduce.", rationale: "Correct. Identify with questions and simple observation." },
      { id: "c", text: "Reimage to save time.", rationale: "Reimage is a later, destructive plan, not identification." },
      { id: "d", text: "Document 'fixed' and close the ticket so the SLA clock stops.", rationale: "Fraudulent closure." },
    ],
    correct: "b",
    explanation: "Identify first: scope, change, reproduction, obvious power. Do not start at replace.",
    sourceBasis: "c1-obj-3.0",
  }),
  q({
    id: "FND-D0-O4-TS-METHOD-Q002",
    objectiveId: "FND-D0-O4",
    conceptIds: ["FND-D0-O4-TS-METHOD"],
    stem: "You tested a theory (bad display cable) and the monitor still fails on a known-good cable. What is NEXT in a sane method?",
    choices: [
      { id: "a", text: "Implement a full motherboard replacement because testing is finished.", rationale: "A failed theory means make a new theory, not jump to the most expensive part." },
      { id: "b", text: "Form a new theory (panel, GPU, source selection) and test that.", rationale: "Correct. The loop returns to theory when the test disproves it." },
      { id: "c", text: "Close the ticket as 'user error.'", rationale: "The fault is still there." },
      { id: "d", text: "Skip documentation because the first theory was wrong.", rationale: "Wrong theories still belong in the notes so nobody repeats them blindly." },
    ],
    correct: "b",
    explanation: "Failed tests send you back to a new probable cause, not to the most expensive guess.",
    sourceBasis: "c1-obj-3.0",
  }),
  q({
    id: "FND-D0-O4-DOCUMENT-Q001",
    objectiveId: "FND-D0-O4",
    conceptIds: ["FND-D0-O4-DOCUMENT"],
    stem: "Which closing note is actually useful to the next technician?",
    choices: [
      { id: "a", text: "PC broken. Fixed.", rationale: "No symptom, no test, no action." },
      { id: "b", text: "User dumb.", rationale: "Unprofessional and empty." },
      { id: "c", text: "Intermittent disconnects after AP firmware Friday. Replaced failing patch cable on port 12; AP remaining on ch 36. User confirmed 20 min soak.", rationale: "Correct. Change, action, evidence, follow-up." },
      { id: "d", text: "See me.", rationale: "Not transferable." },
    ],
    correct: "c",
    explanation: "Good notes capture change, test, action, and verification another person can use.",
    sourceBasis: "c2-obj-3.0",
  }),
  q({
    id: "FND-D0-O5-UNITS-Q001",
    objectiveId: "FND-D0-O5",
    conceptIds: ["FND-D0-O5-UNITS"],
    stem: "A NIC is rated 1 Gbps. A user asks how many megabytes per second that is, approximately, before protocol overhead.",
    choices: [
      { id: "a", text: "1 MB/s", rationale: "Off by about 125×. They confused bits and bytes and the giga prefix." },
      { id: "b", text: "8 MB/s", rationale: "That would be treating 1 Gbps as 8 megabits, then converting poorly." },
      { id: "c", text: "About 125 MB/s theoretical (1,000 Mbps / 8).", rationale: "Correct direction: bits to bytes by dividing by 8. Real transfers are lower." },
      { id: "d", text: "1,000 MB/s", rationale: "That treats bits as bytes." },
    ],
    correct: "c",
    explanation: "Bandwidth is bits per second. Divide by 8 for bytes, then expect overhead.",
    sourceBasis: "rfc791",
  }),
  q({
    id: "FND-D0-O5-UNITS-Q002",
    objectiveId: "FND-D0-O5",
    conceptIds: ["FND-D0-O5-UNITS"],
    stem: "Windows reports a '256 GB' SSD as about 238 GB. What is the usual reason?",
    choices: [
      { id: "a", text: "The rest is always RAID parity.", rationale: "A single SSD is not an array." },
      { id: "b", text: "Vendors often advertise decimal 10^9 bytes while the OS often displays binary 2^30-based units.", rationale: "Correct. Marketing GB vs GiB-style counting." },
      { id: "c", text: "SMART has already retired 18 GB of bad sectors on every new drive.", rationale: "Not a factory default story." },
      { id: "d", text: "UEFI hides a 18 GB recovery partition from every OS.", rationale: "Recovery partitions exist but do not explain this classic mismatch by themselves." },
    ],
    correct: "b",
    explanation: "Decimal vs binary unit conventions explain most 'missing GB' on new disks.",
    sourceBasis: "c1-obj-3.0",
  }),
  q({
    id: "FND-D0-O5-SAFETY-Q001",
    objectiveId: "FND-D0-O5",
    conceptIds: ["FND-D0-O5-SAFETY"],
    stem: "You are about to reseat RAM. Which setup is appropriate?",
    choices: [
      { id: "a", text: "PC plugged in, case on carpet, no strap, RAM tossed on the sofa while you fetch a screwdriver.", rationale: "ESD and mechanical risk stacked." },
      { id: "b", text: "Power disconnected, strap to chassis ground, modules handled by edges, spare parts in antistatic bags.", rationale: "Correct basic ESD hygiene." },
      { id: "c", text: "Strap clipped to a painted cabinet door so it looks professional.", rationale: "Paint is an insulator; that clip does nothing useful." },
      { id: "d", text: "Keep the PSU switched on so the motherboard stays grounded through the outlet.", rationale: "You disconnect power before interior work; 'live grounding' is a myth that gets people hurt." },
    ],
    correct: "b",
    explanation: "Power off, real ground path for the strap, edges, antistatic storage.",
    sourceBasis: "c2-obj-3.0",
  }),
];
