import { objectiveId } from "./ids";
import type { CoreId, Domain, Objective } from "./schema";

function obj(
  core: CoreId,
  domain: number,
  n: number,
  slug: string,
  title: string,
  paraphrase: string,
  examPercent: number,
  subtopics: string[],
  requiredInteractions: string[],
  concepts: string[],
): Objective {
  const id = objectiveId(core, domain, n);
  return {
    id,
    core,
    domain,
    officialCode: `${domain}.${n}`,
    slug,
    title,
    paraphrase,
    examPercent,
    subtopics,
    requiredInteractions,
    conceptIds: concepts.map((c) => `${id}-${c}`),
  };
}

export const FOUNDATION_OBJECTIVES: Objective[] = [
  obj(
    "FND",
    0,
    1,
    "what-is-a-plus",
    "What CompTIA A+ is — and is not",
    "How Core 1 and Core 2 work together, how objectives are weighted, and why this course never claims a guaranteed pass.",
    0,
    [
      "Core 1 vs Core 2",
      "exam structure and question formats",
      "objective numbering",
      "internal readiness vs CompTIA scaled scores",
    ],
    ["exam-map-explorer"],
    ["CERT", "CORES", "SCORES"],
  ),
  obj(
    "FND",
    0,
    2,
    "how-this-course-works",
    "How this academy teaches",
    "Mandatory reading checks, mastery quizzes, labs, spaced review, and how to use the interface without skipping required work.",
    0,
    [
      "learning cycle",
      "knowledge checks",
      "domain gates",
      "review queue",
      "guest vs signed-in progress",
    ],
    ["app-orientation-hotspots"],
    ["CYCLE", "GATES", "REVIEW"],
  ),
  obj(
    "FND",
    0,
    3,
    "exam-language",
    "CompTIA-style language: BEST, FIRST, NEXT",
    "How scenario stems work, how PBQs differ from multiple choice, and how to avoid memorizing wording instead of understanding.",
    0,
    ["BEST/FIRST/NEXT", "PBQ vs MCQ", "distractors", "understanding vs memorization"],
    ["stem-decoder"],
    ["STEMS", "PBQ"],
  ),
  obj(
    "FND",
    0,
    4,
    "troubleshooting-mindset",
    "A practical troubleshooting mindset",
    "A job-practice method for isolating problems. CompTIA V15 does not score the six-step methodology as an exam objective; we still teach it because technicians use it.",
    0,
    [
      "identify the problem",
      "probable cause",
      "test the theory",
      "plan of action",
      "verify and prevent",
      "document",
    ],
    ["method-reorder"],
    ["TS-METHOD", "DOCUMENT"],
  ),
  obj(
    "FND",
    0,
    5,
    "safety-and-units",
    "Safety, documentation, and units",
    "ESD and lifting basics, why tickets matter, and the bits/bytes/bandwidth vocabulary used for the rest of the course.",
    0,
    ["ESD", "PPE", "ticketing mindset", "binary vs decimal units", "bandwidth units"],
    ["it-landscape-hotspots"],
    ["SAFETY", "UNITS", "TICKETS"],
  ),
];

export const CORE1_OBJECTIVES: Objective[] = [
  obj("C1", 1, 1, "laptop-hardware", "Laptop and mobile hardware replacement",
    "Identify replaceable laptop parts, serviceability limits, and failure symptoms before opening a chassis.",
    13, ["battery","keyboard","RAM","HDD/SSD","wireless cards","privacy/security hardware","Wi-Fi antenna placement","camera","microphone","biometrics","near-field scanner"],
    ["laptop-exploded","component-identify","battery-swelling","dimm-vs-sodimm","replace-component"],
    ["BATTERY","KEYBOARD","SODIMM","STORAGE","WLAN","ANTENNA","BIOMETRIC","WEBCAM"]),
  obj("C1", 1, 2, "mobile-accessories", "Mobile accessories and connectivity",
    "Match ports, wireless accessories, docks, and replicators to the job instead of guessing by shape.",
    13, ["USB/USB-C/micro/mini","Lightning","NFC","Bluetooth","tethering/hotspot","stylus","headsets","speakers","webcam","docking station","port replicator","trackpad/drawing pad"],
    ["connector-gallery","identify-port","accessory-match","dock-vs-replicator","bt-pairing"],
    ["USB","LIGHTNING","NFC","BT","DOCK","REPLICATOR"]),
  obj("C1", 1, 3, "mobile-network-sync", "Mobile networking, MDM, and synchronization",
    "Configure cellular, Wi-Fi, Bluetooth pairing, location, mail/contact/calendar sync, and corporate device policy.",
    13, ["3G/4G/5G","hotspot","Wi-Fi","SIM/eSIM","Bluetooth pairing sequence","GPS and cellular location","calendar/contacts/mail/cloud sync","data caps","MDM","BYOD vs corporate","policy enforcement","business apps"],
    ["phone-settings","hotspot-enable","mdm-profile","sync-chooser"],
    ["CELLULAR","ESIM","GPS","SYNC","MDM","BYOD","DATACAP"]),
  obj("C1", 2, 1, "ports-protocols", "TCP, UDP, ports, and common protocols",
    "Explain why a port exists, which transport it uses, and which service broke when that port is blocked.",
    23, ["FTP 20/21","SSH 22","Telnet 23","SMTP 25","DNS 53","DHCP 67/68","HTTP 80","POP3 110","IMAP 143","NetBIOS/NetBT 137-139","LDAP 389","HTTPS 443","SMB/CIFS 445","RDP 3389","TCP vs UDP"],
    ["packet-flow","port-match","tcp-udp-chooser","listening-services","port-drill"],
    ["TCP","UDP","PORTS","FTP","SSH","DNS","DHCP","HTTP","RDP","SMB"]),
  obj("C1", 2, 2, "wireless", "Wireless networking technologies",
    "Choose a band, channel, and 802.11 generation that fit range, interference, and throughput needs.",
    23, ["2.4 GHz","5 GHz","6 GHz","channel regulations and width","Bluetooth","802.11 standards","NFC","RFID"],
    ["spectrum","ap-overlap","channel-selector","wifi-compare"],
    ["24GHZ","5GHZ","6GHZ","80211","RFID","CHANNEL"]),
  obj("C1", 2, 3, "network-hosts", "Networked hosts and internet appliances",
    "Place DNS, DHCP, file, print, mail, web, AAA, syslog, database, NTP, UTM, proxy, load balancer, SCADA, and IoT in a small network.",
    23, ["DNS","DHCP","fileshare","print","mail","syslog","web","AAA","database","NTP","spam gateway","UTM","load balancer","proxy","SCADA","IoT"],
    ["role-builder","hostname-vs-ip"],
    ["DNSSRV","DHCPSRV","AAA","UTM","NTP","SCADA","IOT"]),
  obj("C1", 2, 4, "network-config", "DNS, DHCP, VLAN, and VPN concepts",
    "Read a DNS record, a DHCP pool, and a VLAN/VPN design at A+ depth — not CCNA depth.",
    23, ["A","AAAA","CNAME","MX","TXT","DKIM","SPF","DMARC","DHCP scope/lease/reservation/exclusion","VLAN","VPN"],
    ["dns-builder","dhcp-pool","vlan-viz","vpn-tunnel"],
    ["DNSREC","SPF","DKIM","DMARC","DHCPPOOL","VLAN","VPN"]),
  obj("C1", 2, 5, "network-devices", "Networking hardware devices",
    "Distinguish routers, managed/unmanaged switches, APs, firewalls, patch panels, PoE, cable modems, DSL, ONTs, and NICs.",
    23, ["router","managed switch","unmanaged switch","AP","firewall","patch panel","PoE injector/switch/standards","cable modem","DSL","ONT","NIC","MAC address"],
    ["rack-builder"],
    ["ROUTER","SWITCH","AP","FIREWALL","POE","ONT","NIC","MAC"]),
  obj("C1", 2, 6, "soho-ip", "SOHO addressing and basic router setup",
    "Configure IPv4/IPv6 ideas, public vs private, APIPA, static vs DHCP, mask, gateway, and DNS on a small router.",
    23, ["IPv4 public/private","IPv6","APIPA","static","dynamic","subnet mask","gateway"],
    ["router-admin"],
    ["IPV4","IPV6","APIPA","MASK","GATEWAY","STATIC"]),
  obj("C1", 2, 7, "wan-types", "Internet connections and network types",
    "Pick fiber, cable, DSL, satellite, cellular, or WISP, and name LAN/WAN/PAN/MAN/SAN/WLAN correctly.",
    23, ["satellite","fiber","cable","DSL","cellular","WISP","LAN","WAN","PAN","MAN","SAN","WLAN"],
    ["connection-recommender"],
    ["FIBER","CABLE","DSL","SAT","WISP","LAN","WAN","SAN"]),
  obj("C1", 2, 8, "network-tools", "Networking tools",
    "Choose crimper, stripper, punchdown, tester, toner, loopback, Wi-Fi analyzer, or tap for the fault in front of you.",
    23, ["crimper","cable stripper","punchdown","cable tester","Wi-Fi analyzer","loopback plug","toner probe","network tap"],
    ["tool-bench"],
    ["CRIMPER","PUNCHDOWN","TESTER","TONER","LOOPBACK","TAP","ANALYZER"]),
  obj("C1", 3, 1, "displays", "Display technologies and attributes",
    "Compare LCD IPS/TN/VA, OLED, Mini-LED, digitizers, inverters, and attributes like refresh and gamut.",
    25, ["LCD","IPS","TN","VA","OLED","Mini-LED","touch/digitizer","inverter","pixel density","refresh","resolution","color gamut"],
    ["viewing-angle","refresh-anim","digitizer-layers","display-compare"],
    ["IPS","TN","VA","OLED","MINILED","DIGITIZER","INVERTER"]),
  obj("C1", 3, 2, "cables-connectors", "Cables and connectors",
    "Identify copper categories, T568A/B, fiber, video, USB, storage, and power connectors from verified diagrams — not generated photos.",
    25, ["copper categories","T568A/T568B","coax","STP/UTP","direct burial","plenum","SM/MM fiber","USB 2/3","Thunderbolt","HDMI","DisplayPort","DVI","VGA","USB-C","SATA/eSATA","RJ11","RJ45","F-type","ST","SC","LC","punchdown","micro/mini USB","Molex","Lightning","DB9","adapters"],
    ["connector-museum","t568","punchdown-lab","cable-picker"],
    ["T568","UTP","FIBER","HDMI","USB","SATA","RJ45","MOLEX","DB9"]),
  obj("C1", 3, 3, "ram", "RAM characteristics",
    "Match DIMM vs SODIMM, DDR generation, ECC, and channel layout to a motherboard and a symptom.",
    25, ["SODIMM","DIMM","DDR iterations","ECC vs non-ECC","channel configurations"],
    ["dimm-slots","channel-layout"],
    ["DIMM","SODIMM","DDR","ECC","CHANNELS"]),
  obj("C1", 3, 4, "storage-raid", "Storage devices and RAID",
    "Compare HDD, SSD interfaces, removable/optical media, and RAID 0/1/5/6/10 — including why RAID is not a backup.",
    25, ["spindle speeds","2.5/3.5","NVMe","SATA SSD","PCIe","SAS","M.2","mSATA","RAID 0/1/5/6/10","flash","memory cards","optical"],
    ["raid-lab","raid-capacity","fail-drive"],
    ["HDD","SSD","NVME","M2","RAID0","RAID1","RAID5","RAID6","RAID10"]),
  obj("C1", 3, 5, "motherboard-cpu", "Motherboards, CPUs, firmware, and expansion",
    "Install a CPU, RAM, storage, and GPU on the right form factor, then set UEFI, Secure Boot, TPM, and cooling.",
    25, ["ATX","microATX","ITX","PCI/PCIe","power connectors","SATA/eSATA","headers","M.2","AMD/Intel sockets","multisocket","UEFI/BIOS","Secure Boot","TPM","HSM","x86/x64/ARM","cores","sound/video/capture/NIC cards","fans","heatsink","paste","liquid"],
    ["motherboard-explorer","pc-assembly"],
    ["ATX","PCIE","UEFI","TPM","HSM","ARM","COOLING","CPU"]),
  obj("C1", 3, 6, "psu", "Power supplies",
    "Select wattage, input voltage region, rails, 24-pin/EPS/PCIe/SATA cables, modularity, and redundant PSUs.",
    25, ["110-120 vs 220-240 VAC","3.3/5/12 V","20+4 pin","redundant PSU","modular","wattage","efficiency"],
    ["psu-calculator","psu-cables"],
    ["VAC","RAILS","ATX24","MODULAR","WATTAGE"]),
  obj("C1", 3, 7, "printer-deploy", "Printer and MFD deployment",
    "Unbox, place, driver, firmware, connectivity, sharing, scan destinations, ADF, and secure print.",
    25, ["unbox/placement","PCL vs PostScript","firmware","USB/Ethernet/wireless","printer share","print server","duplex/orientation/trays/quality","auth/badging/audit/secured prints","email/SMB/cloud scan","ADF/flatbed"],
    ["printer-panel"],
    ["PCL","PS","ADF","SECUREPRINT","PRINTSERVER"]),
  obj("C1", 3, 8, "printer-maint", "Printer maintenance",
    "Maintain laser, inkjet, thermal, and impact printers with the right kit, not a generic 'clean it' answer.",
    25, ["laser toner/kit/calibrate/clean","inkjet cartridge/head/roller/feeder","thermal paper/element/debris","impact ribbon/head/multipart paper"],
    ["printer-cutaway","maint-order"],
    ["LASER","INKJET","THERMAL","IMPACT","FUSER","DRUM"]),
  obj("C1", 4, 1, "virtualization", "Virtualization concepts",
    "Explain VMs, Type 1 vs Type 2 hypervisors, VDI, containers, and resource/security requirements.",
    11, ["sandbox","test/dev","legacy/cross-platform","VDI","containers","Type 1","Type 2","network/storage/security requirements"],
    ["stack-builder","type-compare","vm-vs-container"],
    ["VM","TYPE1","TYPE2","VDI","CONTAINER"]),
  obj("C1", 4, 2, "cloud", "Cloud computing concepts",
    "Match public/private/hybrid/community and IaaS/PaaS/SaaS to metered use, elasticity, and shared vs dedicated resources.",
    11, ["private/public/hybrid/community","IaaS","SaaS","PaaS","shared vs dedicated","metered ingress/egress","elasticity","availability","file sync","multitenancy"],
    ["cloud-chooser","elasticity-slider"],
    ["IAAS","PAAS","SAAS","HYBRID","ELASTIC","MULTITENANT"]),
  obj("C1", 5, 1, "ts-system", "Troubleshoot motherboard, RAM, CPU, and power",
    "Map POST beeps, blank screens, no-power, heat, smell, capacitor swelling, and clock drift to a first test.",
    28, ["POST beeps","crash screens","blank screen","no power","sluggish","overheating","burning smell","random shutdown","app crashes","unusual noise","capacitor swelling","wrong date/time"],
    ["ticket-system-board"],
    ["POST","NOPOWER","OVERHEAT","CAPACITOR","CMOS"]),
  obj("C1", 5, 2, "ts-storage", "Troubleshoot drives and RAID",
    "Read SMART, clicking/grinding, missing arrays, degraded RAID, and slow I/O without confusing a failed disk with a failed OS.",
    28, ["LED status","grinding","clicking","boot device not found","corruption","RAID failure","SMART","slow IOPS","missing drives","missing array","alarms"],
    ["raid-console"],
    ["SMART","CLICKING","RAIDFAIL","IOPS"]),
  obj("C1", 5, 3, "ts-display", "Troubleshoot displays and projectors",
    "Separate source, cable, bulb, burn-in, dead pixels, color, audio, and projector thermal faults.",
    28, ["wrong source","cabling","bulb","fuzzy","burn-in","dead pixels","flashing","color","audio","dim","projector shutdown","sizing","distortion"],
    ["display-faults"],
    ["SOURCE","BURNIN","DEADPIXEL","PROJECTOR"]),
  obj("C1", 5, 4, "ts-mobile", "Troubleshoot mobile devices",
    "Inspect battery swell, charging, liquid, digitizer, ports, malware, stylus, and performance on phones and laptops.",
    28, ["battery health","swollen battery","broken screen","charging","connectivity","liquid","heat","digitizer","damaged ports","malware","cursor drift","app install","stylus","degraded performance"],
    ["device-inspect"],
    ["SWELL","DIGITIZER","LIQUID","MOBILEMALWARE"]),
  obj("C1", 5, 5, "ts-network", "Troubleshoot networks",
    "Separate Wi-Fi interference, limited connectivity, DNS, latency/jitter/VoIP, port flapping, and authentication failures.",
    28, ["intermittent wireless","slow speeds","limited connectivity","jitter","poor VoIP","port flapping","high latency","interference","auth failures","intermittent internet"],
    ["wifi-analyzer","ping-jitter","path-lab"],
    ["LIMITED","JITTER","VOIP","FLAPPING","LATENCY"]),
  obj("C1", 5, 6, "ts-printer", "Troubleshoot printers",
    "Match faded, streaked, ghosted, speckled, jammed, garbled, and finishing faults to a subsystem and a first action.",
    28, ["lines","garbled","jams","faded","not feeding","multipage misfeed","queue","speckling","ghosting","grinding","staple/hole punch","orientation","tray not recognized","connectivity","frozen queue"],
    ["output-matcher"],
    ["FADED","GHOST","JAM","GARBLED","QUEUE"]),
];

export const CORE2_OBJECTIVES: Objective[] = [
  obj("C2", 1, 1, "os-types", "Operating system types and purposes",
    "Choose Windows, Linux, macOS, ChromeOS, iOS/iPadOS, or Android using filesystem, lifecycle, and compatibility constraints.",
    28, ["Windows","Linux","macOS","ChromeOS","iPadOS","iOS","Android","NTFS","ReFS","FAT32","ext4","XFS","APFS","exFAT","EOL","update limits","cross-OS compatibility"],
    ["os-matrix"],
    ["WIN","LINUX","MAC","CHROMEOS","FS","EOL"]),
  obj("C2", 1, 2, "os-install", "OS installation, partitions, and upgrades",
    "Pick clean, upgrade, image, remote, zero-touch, or repair installs and GPT/MBR plus the right filesystem.",
    28, ["USB/network/flash/internet/external/internal/multiboot","clean/upgrade/image/remote/zero-touch/recovery/repair","third-party drivers","GPT","MBR","format","upgrade backups/compat","feature updates"],
    ["install-wizard","partition-disk"],
    ["CLEAN","IMAGE","ZEROTOUCH","GPT","MBR"]),
  obj("C2", 1, 3, "windows-editions", "Windows 10 and 11 editions",
    "Match Home/Pro/Enterprise/Pro for Workstations to domain join, RDP host, BitLocker, gpedit, RAM limits, and TPM/UEFI needs.",
    28, ["Win10 Home/Pro/Pro for Workstations/Enterprise","Win11 Home/Pro/Enterprise","N versions","domain vs workgroup","RDP availability","RAM limits","BitLocker","gpedit.msc","in-place vs clean","TPM","UEFI"],
    ["edition-cards"],
    ["HOME","PRO","ENT","BITLOCKER","GPEDIT","TPMWIN"]),
  obj("C2", 1, 4, "windows-tools", "Windows administrative tools",
    "Use Task Manager and MMC snap-ins as simplified educational replicas of real workflows.",
    28, ["Task Manager","eventvwr","diskmgmt","taskschd","devmgmt","certmgr","lusrmgr","perfmon","gpedit","msinfo32","resmon","msconfig","cleanmgr","dfrgui","regedit"],
    ["task-manager","event-viewer","disk-mgmt"],
    ["TASKMGR","EVENTVWR","DISKMGMT","MMC"]),
  obj("C2", 1, 5, "windows-cli", "Windows command-line tools",
    "Run a sandboxed command prompt that models ipconfig, ping, disk, and policy commands without touching the host.",
    28, ["cd","dir","ipconfig","ping","netstat","nslookup","net use","tracert","pathping","chkdsk","format","diskpart","md","rmdir","robocopy","hostname","net user","winver","whoami","/? ","gpupdate","gpresult","sfc"],
    ["cmd-lab"],
    ["IPCONFIG","PING","SFC","DISKPART","GPUPDATE"]),
  obj("C2", 1, 6, "windows-settings", "Windows settings and Control Panel utilities",
    "Complete missions in a simplified Settings/Control Panel replica covering power, network, privacy, and Explorer options.",
    28, ["Internet Options","Devices and Printers","Programs and Features","Network and Sharing","System","Defender Firewall","Mail","Sound","User Accounts","Device Manager","Indexing","Admin Tools","File Explorer Options","Power Options","Ease of Access","Time/Language","Update and Security","Personalization","Apps","Privacy","Accounts","Gaming"],
    ["settings-missions"],
    ["POWER","FIREWALL","INDEXING","EXPLOREROPT"]),
  obj("C2", 1, 7, "windows-network", "Windows client networking",
    "Repair workgroup vs domain, shares, VPN, firewall profile, proxy, and static/DHCP addressing on a workstation.",
    28, ["domain vs workgroup","shares/printers/mapped drives","VPN/wireless/wired/WWAN","local firewall","proxy","public vs private","UNC paths","metered","IP/DNS/mask/gateway/static vs dynamic"],
    ["workstation-repair"],
    ["WORKGROUP","DOMAINJOIN","UNC","METERED","PROXY"]),
  obj("C2", 1, 8, "macos", "macOS tools and features",
    "Support .dmg/.pkg/.app installs, System Settings, Time Machine, FileVault, Keychain, Continuity, and RSR patches.",
    28, ["dmg/pkg/app/App Store","Displays/Networks/Printers/Privacy/Accessibility/Time Machine","/Applications /Users /Library /System","Mission Control","Keychain","Spotlight","iCloud","FileVault","Disk Utility","Terminal","Force Quit","RSR","Continuity"],
    ["macos-sim"],
    ["DMG","TIMEMACHINE","FILEVAULT","KEYCHAIN","RSR"]),
  obj("C2", 1, 9, "linux", "Linux client tools and files",
    "Navigate a virtual Linux filesystem and use the objective-listed commands and /etc files.",
    28, ["ls/pwd/mv/cp/rm/chmod/chown/grep/find","fsck/mount","su/sudo","apt/dnf","ip/ping/curl/dig/traceroute","man/cat/top/ps/du/df","nano","passwd/shadow/hosts/fstab/resolv.conf","systemd/kernel/bootloader","root"],
    ["linux-term"],
    ["CHMOD","SUDO","APT","SYSTEMD","ETC"]),
  obj("C2", 1, 10, "app-install", "Application installation requirements",
    "Check 32/64-bit, GPU/VRAM, RAM, CPU, tokens, OS compatibility, and distribution method before installing.",
    28, ["32 vs 64-bit","dedicated vs integrated GPU","VRAM/RAM/CPU/storage","hardware tokens","OS compatibility","physical vs ISO vs download vs image","device/network/operation/business impact"],
    ["install-targets"],
    ["X86APP","VRAM","ISO","IMPACT"]),
  obj("C2", 1, 11, "cloud-productivity", "Cloud-based productivity",
    "Configure email, storage sync, identity sync, licensing, and collaboration tools for a fictional employee.",
    28, ["email","storage sync/folder settings","spreadsheets","video meetings","presentations","docs","IM","identity sync","licensing"],
    ["cloud-account"],
    ["EMAILSYNC","LICENSE","COLLAB"]),
  obj("C2", 2, 1, "security-controls", "Physical and logical security controls",
    "Place bollards, vestibules, badges, MFA, Zero Trust, SAML, JIT/PAM, MDM, DLP, and IAM on a realistic office problem.",
    28, ["bollards","access control vestibule","badges","cameras","alarms","motion","locks","guards","fences","fobs/smart cards/mobile keys","biometrics","lighting","magnetometers","least privilege","Zero Trust","ACLs","MFA","SAML","SSO","JIT/PAM","MDM","DLP","IAM","directory"],
    ["floorplan-controls","iam-design"],
    ["VESTIBULE","ZEROTRUST","MFA","SAML","PAM","DLP","IAM"]),
  obj("C2", 2, 2, "windows-security", "Windows OS security settings",
    "Configure Defender, firewall, accounts, NTFS vs share permissions, UAC, BitLocker, EFS, and Active Directory basics.",
    28, ["Defender","firewall","local vs Microsoft accounts","NTFS vs share + inheritance","UAC","BitLocker/To Go","EFS","AD join/OU/GPO/logon script/home folders/redirection/security groups","Windows Hello/SSO"],
    ["permissions-sim"],
    ["NTFS","SHAREPERM","UAC","EFS","AD","HELLO"]),
  obj("C2", 2, 3, "wireless-security", "Wireless security protocols",
    "Harden an AP with WPA2/WPA3, AES vs TKIP, and RADIUS/TACACS+/Kerberos/MFA.",
    28, ["WPA2","WPA3","TKIP","AES","RADIUS","TACACS+","Kerberos","multifactor"],
    ["ap-harden"],
    ["WPA2","WPA3","AES","RADIUS","KERBEROS"]),
  obj("C2", 2, 4, "malware", "Malware types and detection tools",
    "Name Trojan, ransomware, fileless, stalkerware, cryptominer, and the difference between EDR, MDR, and XDR at A+ depth.",
    28, ["Trojan","rootkit","virus","spyware","ransomware","keylogger","boot sector","cryptominer","stalkerware","fileless","adware","PUP","recovery console","EDR","MDR","XDR","AV/AM","email gateway","software firewall","user education","reinstall"],
    ["threat-cards"],
    ["RANSOM","FILELESS","EDR","XDR","PUP"]),
  obj("C2", 2, 5, "attacks", "Social engineering, attacks, and vulnerabilities",
    "Identify phishing variants, evil twin, on-path, BEC, XSS/SQLi conceptually, and unpatched/BYOD risk.",
    28, ["phishing/vishing/smishing/QR/spear/whaling","shoulder surfing","tailgating","impersonation","dumpster diving","DoS/DDoS","evil twin","zero-day","spoofing","on-path","brute/dictionary","insider","SQLi","XSS","BEC","supply chain","noncompliant/unpatched/unprotected/EOL/BYOD"],
    ["phish-inbox","evil-twin","vishing"],
    ["PHISH","BEC","EVILTWIN","ONPATH","XSS"]),
  obj("C2", 2, 6, "malware-removal", "SOHO malware removal process",
    "Restore the current 10-step CompTIA SOHO malware-removal order and explain why each step exists.",
    28, ["investigate/verify","quarantine","disable System Restore (Windows Home)","remediate","update anti-malware","scan/removal (safe mode/PE)","reimage/reinstall","schedule scans/updates","enable System Restore + restore point","educate user"],
    ["malware-order","infection-sim"],
    ["QUARANTINE","SYSRESTORE","REIMAGE"]),
  obj("C2", 2, 7, "workstation-harden", "Workstation hardening",
    "Raise a workstation from a weak baseline using encryption, passwords, lockout, unused services, and AutoRun risk.",
    28, ["data-at-rest encryption","password length/types/uniqueness/complexity/expiration","BIOS/UEFI passwords","screensaver/logoff/PII","restrict permissions/logon hours","disable guest","lockout","timeout","expiration","change default admin","disable AutoRun","disable unused services","OS/app patching","endpoint AV/AM/content filter"],
    ["posture-scorer"],
    ["HARDEN","AUTORUN","LOCKOUT","BIOSPW"]),
  obj("C2", 2, 8, "mobile-security", "Mobile device security",
    "Apply encryption, screen locks, locator, remote wipe, MDM, and BYOD vs corporate profiles.",
    28, ["device encryption","face/PIN/fingerprint/pattern/swipe","configuration profiles","locator","remote wipe","remote backup","failed logon limits","MDM","BYOD vs corporate"],
    ["phone-harden"],
    ["REMOTEWIPE","SCREENLOCK","MDMPROFILE"]),
  obj("C2", 2, 9, "destruction", "Data destruction and disposal",
    "Choose drilling, shredding, degaussing, incineration, wipe, or low-level format for the media in front of you.",
    28, ["drill","shred","degauss","incinerate","erase/wipe","low-level format","standard format","third-party CoD","regulatory/environmental"],
    ["disposal-chooser"],
    ["DEGAUSS","WIPE","SHRED","COD"]),
  obj("C2", 2, 10, "soho-secure", "Secure SOHO wired and wireless networks",
    "Change defaults, update firmware, set WPA3, guest, SSID, UPnP, firewall, port forward, and screened-subnet ideas.",
    28, ["default passwords","IP/content filtering","firmware","placement","UPnP","screened subnet","secure management","SSID change/disable broadcast","encryption","guest","disable unused ports","port forwarding"],
    ["router-security"],
    ["UPNP","SSID","PORTFWD","DMZ"]),
  obj("C2", 2, 11, "browser-security", "Browser security settings",
    "Inspect downloads, hashes, extensions, certificates, pop-ups, cache, private mode, ad blockers, proxy, and secure DNS.",
    28, ["trusted vs untrusted download","hashing","patching","extensions","password managers","certificates","pop-up blocker","clear data/cache","private browsing","sync","ad blockers","proxy","secure DNS","feature enable/disable"],
    ["browser-sim"],
    ["CERTWARN","HASH","PRIVACYMODE","SECUREDNS"]),
  obj("C2", 3, 1, "ts-windows", "Troubleshoot Windows OS issues",
    "Drive BSOD, boot, profile, time drift, service, memory, and USB-resource problems with the right tool.",
    23, ["BSOD","degraded performance","boot","frequent shutdowns","services","app crashes","low memory","USB controller resource","system instability","no OS found","slow profile","time drift"],
    ["windows-ts-desktop"],
    ["BSOD","PROFILE","TIMEDRIFT","USBRES"]),
  obj("C2", 3, 2, "ts-mobile-os", "Troubleshoot mobile OS and apps",
    "Fix launch/crash/update/install failures, battery software symptoms, radios, and autorotate.",
    23, ["fail to launch/close/update/install","slow","OS update fail","battery life","BT/Wi-Fi/NFC","autorotate"],
    ["phone-os-ts"],
    ["APPCRASH","AUTOROTATE","MOBILEUPDATE"]),
  obj("C2", 3, 3, "ts-mobile-sec", "Troubleshoot mobile security symptoms",
    "Recognize unofficial stores, developer mode, root/jailbreak, spoofed apps, data-usage spikes, and leaked files.",
    23, ["unofficial stores","developer mode","root/jailbreak","malicious/spoofed apps","high traffic","slow response","data-usage limit","limited/no internet","ads","fake warnings","unexpected behavior","leaked data"],
    ["compromised-phone"],
    ["JAILBREAK","SPOOFAPP","DATAUSAGE"]),
  obj("C2", 3, 4, "ts-pc-sec", "Troubleshoot PC security symptoms",
    "Investigate redirects, certificate warnings, fake AV, missing files, failed updates, and unwanted notifications.",
    23, ["no network","desktop alerts","false AV","altered/missing files","unwanted notifications","OS update failures","browser pop-ups/certs/redirects/slow browser"],
    ["compromised-pc"],
    ["REDIRECT","FAKEAV","CERTBROWSER"]),
  obj("C2", 4, 1, "documentation", "Documentation, ticketing, and asset management",
    "Turn 'PC broken' into a usable ticket with severity, notes, CMDB, SOP, SLA, and onboarding/offboarding.",
    21, ["ticket fields","severity/escalation","asset inventory/CMDB/tags","procurement/warranty/licensing","incident reports","SOP","onboarding/offboarding","SLA","knowledge base"],
    ["ticket-lab"],
    ["TICKET","CMDB","SLA","SOP"]),
  obj("C2", 4, 2, "change", "Change management",
    "Walk a standard, normal, or emergency change through rollback, freeze windows, CAB, and acceptance.",
    21, ["rollback/backup/sandbox/owners","request/purpose/scope","standard/normal/emergency","freeze/maintenance window","impact","risk","CAB","implement","peer review","user acceptance"],
    ["change-pipeline"],
    ["CAB","ROLLBACK","FREEZE","EMERGENCY"]),
  obj("C2", 4, 3, "backup", "Backups and recovery",
    "Compare full, incremental, differential, and synthetic full, then restore with GFS and 3-2-1.",
    21, ["full","incremental","differential","synthetic full","in-place vs alternate location","testing/frequency","onsite/offsite","GFS","3-2-1"],
    ["backup-timeline","restore-chain","gfs-calendar"],
    ["FULL","INCR","DIFF","GFS","321"]),
  obj("C2", 4, 4, "safety", "Safety procedures",
    "Make a bench safe with ESD, grounding, disconnecting power, lifting, fire, and PPE before opening a PC.",
    21, ["ESD strap/mat","grounding","component handling","cable management","antistatic bags","disconnect power","lifting","fire","goggles","air filter mask","regulations"],
    ["safe-bench"],
    ["ESD","GROUND","PPE","LIFT"]),
  obj("C2", 4, 5, "environment", "Environmental and power controls",
    "Use MSDS, battery/toner disposal, UPS vs surge, and temperature/humidity/dust controls in a small IT room.",
    21, ["MSDS","battery/toner/asset disposal","temperature/humidity/ventilation","placement","dust/compressed air/vacuum","surge/brownout/blackout","UPS","surge suppressor"],
    ["it-room"],
    ["MSDS","UPS","BROWNOUT","HUMIDITY"]),
  obj("C2", 4, 6, "privacy-incident", "Privacy, licensing, and incident handling",
    "Preserve evidence with chain of custody and order of volatility, and handle PII, licenses, AUP, and NDAs.",
    21, ["chain of custody","management/LE","drive copy","order of volatility","EULA/DRM/open source/perpetual vs personal vs corporate","NDA/MNDA","payment/gov/PII/health/retention","AUP","splash screens"],
    ["evidence-timeline"],
    ["COC","VOLATILITY","PII","EULA","AUP"]),
  obj("C2", 4, 7, "professionalism", "Professional communication",
    "Choose believable BEST responses for angry, confused, executive, and vague customers — not cartoon professionalism.",
    21, ["attire","language","listening","cultural sensitivity","punctuality","distractions","difficult customers","expectations","confidential materials"],
    ["voice-shift"],
    ["LISTEN","DIFFICULT","CONFIDENTIAL"]),
  obj("C2", 4, 8, "scripting", "Scripting basics",
    "Recognize .bat/.ps1/.vbs/.sh/.js/.py use cases and the risk of malware, config drift, and resource exhaustion. Never execute learner code server-side.",
    21, [".bat",".ps1",".vbs",".sh",".js",".py","automation/restart/map/install/backup/inventory/update","malware","settings change","crashes"],
    ["script-viewer"],
    ["PS1","BAT","PY","SCRIPTRISK"]),
  obj("C2", 4, 9, "remote-access", "Remote access technologies",
    "Choose RDP, VPN, VNC, SSH, RMM, SPICE, WinRM, or third-party screen share with the security tradeoff named.",
    21, ["RDP","VPN","VNC","SSH","RMM","SPICE","WinRM","screen share/video/file transfer/desktop management","security per method"],
    ["remote-chooser"],
    ["RDP","VNC","RMM","WINRM","SPICE"]),
  obj("C2", 4, 10, "ai-fundamentals", "Artificial intelligence fundamentals",
    "Apply appropriate-use policy, private vs public tools, and the limits of bias, hallucination, and accuracy. A technician must verify AI output.",
    21, ["application integration","appropriate use","plagiarism","bias","hallucinations","accuracy","private vs public","data security/source/privacy"],
    ["ai-scenarios"],
    ["HALLUCINATION","AIPOLICY","PRIVATEAI"]),
];

export const ALL_OBJECTIVES: Objective[] = [
  ...FOUNDATION_OBJECTIVES,
  ...CORE1_OBJECTIVES,
  ...CORE2_OBJECTIVES,
];

export const DOMAINS: Domain[] = [
  {
    id: "FND-D0",
    core: "FND",
    number: 0,
    slug: "foundation",
    title: "Course orientation and IT foundations",
    examPercent: 0,
    paraphrase: "Required onboarding before Core 1. Not an exam domain.",
    objectiveIds: FOUNDATION_OBJECTIVES.map((o) => o.id),
  },
  {
    id: "C1-D1",
    core: "C1",
    number: 1,
    slug: "mobile-devices",
    title: "Mobile Devices",
    examPercent: 13,
    paraphrase: "Laptops, phones, accessories, cellular/Wi-Fi, and MDM.",
    objectiveIds: CORE1_OBJECTIVES.filter((o) => o.domain === 1).map((o) => o.id),
  },
  {
    id: "C1-D2",
    core: "C1",
    number: 2,
    slug: "networking",
    title: "Networking",
    examPercent: 23,
    paraphrase: "Protocols, wireless, hosts, SOHO IP, WAN types, and tools.",
    objectiveIds: CORE1_OBJECTIVES.filter((o) => o.domain === 2).map((o) => o.id),
  },
  {
    id: "C1-D3",
    core: "C1",
    number: 3,
    slug: "hardware",
    title: "Hardware",
    examPercent: 25,
    paraphrase: "Displays, cables, RAM, storage/RAID, motherboards, PSU, printers.",
    objectiveIds: CORE1_OBJECTIVES.filter((o) => o.domain === 3).map((o) => o.id),
  },
  {
    id: "C1-D4",
    core: "C1",
    number: 4,
    slug: "virtualization-cloud",
    title: "Virtualization and Cloud Computing",
    examPercent: 11,
    paraphrase: "Hypervisors, containers, VDI, and cloud models.",
    objectiveIds: CORE1_OBJECTIVES.filter((o) => o.domain === 4).map((o) => o.id),
  },
  {
    id: "C1-D5",
    core: "C1",
    number: 5,
    slug: "hardware-network-troubleshooting",
    title: "Hardware and Network Troubleshooting",
    examPercent: 28,
    paraphrase: "System, storage, display, mobile, network, and printer faults.",
    objectiveIds: CORE1_OBJECTIVES.filter((o) => o.domain === 5).map((o) => o.id),
  },
  {
    id: "C2-D1",
    core: "C2",
    number: 1,
    slug: "operating-systems",
    title: "Operating Systems",
    examPercent: 28,
    paraphrase: "Windows, macOS, Linux, installs, editions, tools, and cloud apps.",
    objectiveIds: CORE2_OBJECTIVES.filter((o) => o.domain === 1).map((o) => o.id),
  },
  {
    id: "C2-D2",
    core: "C2",
    number: 2,
    slug: "security",
    title: "Security",
    examPercent: 28,
    paraphrase: "Controls, Windows/mobile/SOHO hardening, malware, and browsers.",
    objectiveIds: CORE2_OBJECTIVES.filter((o) => o.domain === 2).map((o) => o.id),
  },
  {
    id: "C2-D3",
    core: "C2",
    number: 3,
    slug: "software-troubleshooting",
    title: "Software Troubleshooting",
    examPercent: 23,
    paraphrase: "Windows, mobile OS, and security-symptom diagnosis.",
    objectiveIds: CORE2_OBJECTIVES.filter((o) => o.domain === 3).map((o) => o.id),
  },
  {
    id: "C2-D4",
    core: "C2",
    number: 4,
    slug: "operational-procedures",
    title: "Operational Procedures",
    examPercent: 21,
    paraphrase: "Tickets, change, backup, safety, professionalism, scripting, remote access, AI.",
    objectiveIds: CORE2_OBJECTIVES.filter((o) => o.domain === 4).map((o) => o.id),
  },
];

export function getObjective(id: string): Objective | undefined {
  return ALL_OBJECTIVES.find((o) => o.id === id);
}

export function getDomain(id: string): Domain | undefined {
  return DOMAINS.find((d) => d.id === id);
}

export function objectivesForDomain(domainId: string): Objective[] {
  const domain = getDomain(domainId);
  if (!domain) return [];
  return ALL_OBJECTIVES.filter((o) => domain.objectiveIds.includes(o.id));
}
