import type { Source } from "./schema";

export const SOURCES: Source[] = [
  {
    id: "comptia-a-v15",
    title: "CompTIA A+ Core 1 and Core 2 V15 certification page",
    url: "https://www.comptia.org/en-us/certifications/a/core-1-and-2-v15/",
    group: "certification",
    verified: "2026-09-01",
  },
  {
    id: "c1-obj-3.0",
    title: "CompTIA A+ 220-1201 Exam Objectives v3.0",
    url: "https://assets.ctfassets.net/82ripq7fjls2/1oSdlyujpaX3GrM0rir6Ge/91afb2be72785281e8fb4c0d9a70c6f4/CompTIA-A-220-1201-Exam-Objectives-3.0.pdf",
    group: "certification",
    verified: "2026-09-01",
  },
  {
    id: "c2-obj-3.0",
    title: "CompTIA A+ 220-1202 Exam Objectives v3.0",
    url: "https://assets.ctfassets.net/82ripq7fjls2/6I8WL66IBa1AUovioDGrnM/f74a7eca336fd4e4c8e723a1f893086d/CompTIA-A-220-1202-Exam-Objectives-3.0.pdf",
    group: "certification",
    verified: "2026-09-01",
  },
  {
    id: "ms-windows",
    title: "Microsoft Learn — Windows client documentation",
    url: "https://learn.microsoft.com/windows/",
    group: "windows",
    verified: "2026-09-01",
  },
  {
    id: "ms-bitlocker",
    title: "Microsoft Learn — BitLocker",
    url: "https://learn.microsoft.com/windows/security/operating-system-security/data-protection/bitlocker/",
    group: "windows",
    verified: "2026-09-01",
  },
  {
    id: "apple-macos",
    title: "Apple macOS User Guide",
    url: "https://support.apple.com/guide/mac-help/welcome/mac",
    group: "macos",
    verified: "2026-09-01",
  },
  {
    id: "apple-filevault",
    title: "Apple — Encrypt Mac data with FileVault",
    url: "https://support.apple.com/102522",
    group: "macos",
    verified: "2026-09-01",
  },
  {
    id: "debian-ref",
    title: "Debian Reference — GNU/Linux administration",
    url: "https://www.debian.org/doc/manuals/debian-reference/",
    group: "linux",
    verified: "2026-09-01",
  },
  {
    id: "man7",
    title: "Linux man-pages project",
    url: "https://man7.org/linux/man-pages/",
    group: "linux",
    verified: "2026-09-01",
  },
  {
    id: "rfc791",
    title: "RFC 791 — Internet Protocol",
    url: "https://www.rfc-editor.org/rfc/rfc791",
    group: "networking",
    verified: "2026-09-01",
  },
  {
    id: "rfc1034",
    title: "RFC 1034 — Domain names",
    url: "https://www.rfc-editor.org/rfc/rfc1034",
    group: "networking",
    verified: "2026-09-01",
  },
  {
    id: "wifi-alliance",
    title: "Wi-Fi Alliance — Wi-Fi 6 / 6E",
    url: "https://www.wi-fi.org/",
    group: "standards",
    verified: "2026-09-01",
  },
  {
    id: "usb-if",
    title: "USB-IF — USB specifications overview",
    url: "https://www.usb.org/",
    group: "standards",
    verified: "2026-09-01",
  },
  {
    id: "nist-800-88",
    title: "NIST SP 800-88 Rev. 1 — Media Sanitization",
    url: "https://csrc.nist.gov/publications/detail/sp/800-88/rev-1/final",
    group: "security",
    verified: "2026-09-01",
  },
  {
    id: "cisa-phishing",
    title: "CISA — Phishing guidance",
    url: "https://www.cisa.gov/topics/cybersecurity-best-practices",
    group: "security",
    verified: "2026-09-01",
  },
  {
    id: "pcie-sig",
    title: "PCI-SIG — PCI Express",
    url: "https://pcisig.com/",
    group: "hardware",
    verified: "2026-09-01",
  },
];
