import { q } from "../../question-factory";
import type { Question } from "../../schema";

export const C1_D4_QUESTIONS: Question[] = [
  q({
    id: "C1-D4-O1-VM-Q001",
    objectiveId: "C1-D4-O1",
    conceptIds: ["C1-D4-O1-VM"],
    difficulty: "intro",
    stem: "A technician creates a virtual machine on a workstation. Which statement correctly names the pieces?",
    choices: [
      { id: "a", text: "The VM is the host; the physical PC is the guest.", rationale: "Reversed. The physical PC is the host; each VM is a guest." },
      { id: "b", text: "The physical PC is the host; the VM is a guest running on a hypervisor.", rationale: "Correct. Host hardware, hypervisor, guest OS." },
      { id: "c", text: "The hypervisor is the guest; the VM is Type 3 firmware.", rationale: "There is no Type 3 firmware class on the A+ objective. The hypervisor is not a guest." },
      { id: "d", text: "A VM is only a container that shares the host kernel.", rationale: "That describes a container, not a VM." },
    ],
    correct: "b",
    explanation: "A virtual machine is a guest OS scheduled by a hypervisor on a physical host.",
    remediationLessonId: "C1-D4-O1-L1",
    tags: ["terminology"],
  }),
  q({
    id: "C1-D4-O1-VM-Q002",
    objectiveId: "C1-D4-O1",
    conceptIds: ["C1-D4-O1-VM"],
    type: "scenario",
    scenario: "Three VMs on one host are each given 16 GB of RAM. The host has 32 GB. Two guests fail to power on after a reboot.",
    stem: "What is the MOST likely cause?",
    choices: [
      { id: "a", text: "The guests need more vCPUs, not RAM.", rationale: "The failure is power-on of memory-sized guests, not CPU count." },
      { id: "b", text: "RAM was over-allocated; the host cannot satisfy all reservations at once.", rationale: "Correct. 3 × 16 GB exceeds 32 GB unless dynamic memory actually reclaims enough — and many guests will not start." },
      { id: "c", text: "VMs cannot run after a host reboot by design.", rationale: "Autostart is configurable; reboot is not a ban on VMs." },
      { id: "d", text: "The hypervisor converted the VMs into containers and dropped RAM.", rationale: "Hypervisors do not silently convert guests into containers." },
    ],
    correct: "b",
    explanation: "Memory is a hard start requirement. Over-allocating RAM is a classic reason guests refuse to power on.",
    remediationLessonId: "C1-D4-O1-L1",
    tags: ["scenario"],
  }),
  q({
    id: "C1-D4-O1-VM-Q003",
    objectiveId: "C1-D4-O1",
    conceptIds: ["C1-D4-O1-VM"],
    stem: "A developer needs to test a Windows installer that might be unsafe. Which virtualization use case fits BEST?",
    choices: [
      { id: "a", text: "VDI for the whole company", rationale: "VDI is a desktop farm, not a one-off sandbox." },
      { id: "b", text: "A sandboxed VM that can be reverted to a snapshot", rationale: "Correct. Isolation plus rollback is the sandbox job." },
      { id: "c", text: "A container that shares the host kernel with production", rationale: "Sharing the host kernel is a weaker boundary for untrusted installers." },
      { id: "d", text: "PaaS, because installers are platform services", rationale: "PaaS is a cloud service model, not a local malware sandbox." },
    ],
    correct: "b",
    explanation: "Sandboxing untrusted software is a primary VM use case: isolate, test, revert.",
    remediationLessonId: "C1-D4-O1-L1",
    tags: ["scenario"],
  }),
  q({
    id: "C1-D4-O1-VM-Q004",
    objectiveId: "C1-D4-O1",
    conceptIds: ["C1-D4-O1-VM"],
    stem: "A guest is configured with a host-only virtual NIC. What can it typically reach?",
    choices: [
      { id: "a", text: "The internet via the office default gateway without extra NAT", rationale: "Host-only is isolated from the physical LAN/WAN." },
      { id: "b", text: "The host and other host-only guests, not the production LAN", rationale: "Correct. That is the sandbox-friendly mode." },
      { id: "c", text: "Only cloud IaaS regions", rationale: "Host-only has nothing to do with cloud regions." },
      { id: "d", text: "DHCP on the corporate VLAN automatically", rationale: "It is not on the corporate VLAN." },
    ],
    correct: "b",
    explanation: "Host-only networking keeps guests off the LAN while still allowing host-to-guest traffic.",
    remediationLessonId: "C1-D4-O1-L1",
  }),
  q({
    id: "C1-D4-O1-VM-Q005",
    objectiveId: "C1-D4-O1",
    conceptIds: ["C1-D4-O1-VM"],
    type: "multi",
    stem: "Which TWO requirements apply when you create a production VM? (Choose two.)",
    choices: [
      { id: "a", text: "Enough host RAM and storage for the guest plus overhead", rationale: "Correct. Resources are finite." },
      { id: "b", text: "A guest OS license if the OS requires one", rationale: "Correct. Virtual is not automatically free." },
      { id: "c", text: "A Type 3 hypervisor burned into the CPU", rationale: "Not a thing on this objective." },
      { id: "d", text: "The VM must be a container so it can share RAM with the host kernel only", rationale: "Conflates VMs and containers." },
      { id: "e", text: "The host must disable all physical NICs forever", rationale: "Guests still need a network path when the design calls for it." },
    ],
    correct: ["a", "b"],
    explanation: "You still size hardware and license the guest OS. Virtualization does not erase those requirements.",
    remediationLessonId: "C1-D4-O1-L1",
    tags: ["multi"],
  }),
  q({
    id: "C1-D4-O1-VM-Q006",
    objectiveId: "C1-D4-O1",
    conceptIds: ["C1-D4-O1-VM"],
    stem: "A datastore fills because several thin-provisioned disks grew at once. Guests pause. What happened?",
    choices: [
      { id: "a", text: "Thin provisioning over-committed storage until the volume was full", rationale: "Correct. Thin disks grow; the datastore can still fill." },
      { id: "b", text: "Type 2 hypervisors cannot use disks", rationale: "Type 2 guests use virtual disks on the host just like Type 1." },
      { id: "c", text: "Snapshots automatically compress the datastore to zero", rationale: "Snapshots consume space; they do not empty a datastore." },
      { id: "d", text: "The guests converted to SaaS and no longer need disks", rationale: "SaaS is a cloud service model, not a datastore event." },
    ],
    correct: "a",
    explanation: "Thin provision saves space until many guests write. A full datastore pauses VMs.",
    remediationLessonId: "C1-D4-O1-L1",
  }),
  q({
    id: "C1-D4-O1-VM-Q007",
    objectiveId: "C1-D4-O1",
    conceptIds: ["C1-D4-O1-VM"],
    difficulty: "exam",
    stem: "An accountant still needs a 32-bit line-of-business app that will not run on Windows 11. Which approach matches the virtualization objective?",
    choices: [
      { id: "a", text: "Run the old OS as a maintained guest VM", rationale: "Correct. Legacy/cross-platform is a VM use case — and you still patch the guest." },
      { id: "b", text: "Leave an unpatched physical Windows XP PC on the LAN forever", rationale: "Virtualization exists partly to retire that pattern." },
      { id: "c", text: "Install the 32-bit app as a Linux container on Windows 11", rationale: "A Windows 32-bit app is not a Linux container workload." },
      { id: "d", text: "Convert the app into IaaS metering without an OS", rationale: "IaaS still has an OS. Metering is not a compatibility layer." },
    ],
    correct: "a",
    explanation: "Legacy applications are a listed reason to run a guest OS — still patched and isolated.",
    remediationLessonId: "C1-D4-O1-L1",
  }),
  q({
    id: "C1-D4-O1-VM-Q008",
    objectiveId: "C1-D4-O1",
    conceptIds: ["C1-D4-O1-VM"],
    stem: "Why is a VM snapshot a poor substitute for a backup of a domain controller?",
    choices: [
      { id: "a", text: "Snapshots are crash-consistent roll-back points on the same datastore, not an offsite copy", rationale: "Correct. Same disk failure can take snapshot and VM together; AD also has USN/snapshot caveats." },
      { id: "b", text: "Snapshots always encrypt the guest so restores are impossible", rationale: "Snapshots are not forced encryption; the problem is co-located roll-back points, not crypto." },
      { id: "c", text: "Domain controllers cannot run as VMs", rationale: "They can, with vendor guidance." },
      { id: "d", text: "Only Type 2 hypervisors can snapshot", rationale: "Type 1 platforms snapshot constantly." },
    ],
    correct: "a",
    explanation: "Snapshots are not backups: they live with the VM and are not a replacement for a tested backup chain.",
    remediationLessonId: "C1-D4-O1-L1",
    tags: ["misconception"],
  }),
  q({
    id: "C1-D4-O1-TYPE1-Q001",
    objectiveId: "C1-D4-O1",
    conceptIds: ["C1-D4-O1-TYPE1"],
    difficulty: "intro",
    stem: "Which statement describes a Type 1 hypervisor?",
    choices: [
      { id: "a", text: "It installs as an application on top of Windows 11 Home.", rationale: "That is Type 2 (and Home lacks client Hyper-V)." },
      { id: "b", text: "It runs on the hardware (bare metal) and guests run on the hypervisor.", rationale: "Correct. Type 1 sits on the metal with no general-purpose desktop OS underneath." },
      { id: "c", text: "It is another name for a container engine.", rationale: "Containers share a host kernel; they are not a bare-metal hypervisor class." },
      { id: "d", text: "It can only host one guest.", rationale: "Datacenter Type 1 hosts are built to schedule many guests on one box." },
    ],
    correct: "b",
    explanation: "Type 1 is bare metal: hardware → hypervisor → guests.",
    remediationLessonId: "C1-D4-O1-L2",
    tags: ["terminology"],
  }),
  q({
    id: "C1-D4-O1-TYPE1-Q002",
    objectiveId: "C1-D4-O1",
    conceptIds: ["C1-D4-O1-TYPE1"],
    type: "scenario",
    scenario: "A company wants a rack server that runs 40 VDI desktops with a small attack surface and no local desktop OS for users of the host.",
    stem: "Which hypervisor class is the BEST fit?",
    choices: [
      { id: "a", text: "Type 2 on a gaming laptop", rationale: "Wrong scale and wrong isolation story." },
      { id: "b", text: "Type 1 (bare metal) on the server", rationale: "Correct. Datacenter/VDI is the Type 1 job." },
      { id: "c", text: "A SaaS spreadsheet", rationale: "SaaS is not a hypervisor." },
      { id: "d", text: "A community cloud only, because VDI cannot be on-premises", rationale: "VDI is commonly on-premises Type 1." },
    ],
    correct: "b",
    explanation: "VDI farms and dense server virtualization use Type 1 hypervisors.",
    remediationLessonId: "C1-D4-O1-L2",
  }),
  q({
    id: "C1-D4-O1-TYPE1-Q003",
    objectiveId: "C1-D4-O1",
    conceptIds: ["C1-D4-O1-TYPE1"],
    stem: "A Type 1 host is compromised through its management interface. What is the security implication?",
    choices: [
      { id: "a", text: "Only the management VLAN DNS cache is at risk.", rationale: "Understates the blast radius." },
      { id: "b", text: "Every guest on that host is in the failure domain.", rationale: "Correct. Hypervisor compromise is all guests." },
      { id: "c", text: "Guests with host-only NICs are immune to hypervisor compromise.", rationale: "The attacker is already under the guests." },
      { id: "d", text: "Type 1 hosts cannot be compromised because they have no OS.", rationale: "The hypervisor is software and must be patched." },
    ],
    correct: "b",
    explanation: "Lock down and patch the hypervisor; it sits under every guest.",
    remediationLessonId: "C1-D4-O1-L2",
  }),
  q({
    id: "C1-D4-O1-TYPE1-Q004",
    objectiveId: "C1-D4-O1",
    conceptIds: ["C1-D4-O1-TYPE1"],
    stem: "Which CPU feature must usually be enabled in UEFI for modern 64-bit guests to virtualize properly?",
    choices: [
      { id: "a", text: "Intel VT-x or AMD-V", rationale: "Correct. Hardware virtualization extensions." },
      { id: "b", text: "NX disabled and execute-all", rationale: "The opposite of a hardening step; not the virtualization toggle." },
      { id: "c", text: "CSM/legacy boot only", rationale: "CSM is not the VT-x switch." },
      { id: "d", text: "Secure Boot disabled as a requirement for all Type 1", rationale: "Many Type 1 hosts run with Secure Boot enabled." },
    ],
    correct: "a",
    explanation: "VT-x/AMD-V are the hardware assists Type 1 and Type 2 products expect.",
    remediationLessonId: "C1-D4-O1-L2",
  }),
  q({
    id: "C1-D4-O1-TYPE1-Q005",
    objectiveId: "C1-D4-O1",
    conceptIds: ["C1-D4-O1-TYPE1"],
    stem: "A SAN path to a Type 1 datastore fails. Several VMs go down together. What does that illustrate?",
    choices: [
      { id: "a", text: "Each VM has independent physical disks that cannot fail together", rationale: "Wrong — those guests shared one datastore path, so they fail together." },
      { id: "b", text: "Shared storage is a shared failure domain for those guests", rationale: "Correct. One SAN/NAS outage pauses every VM on that datastore." },
      { id: "c", text: "Type 1 cannot use shared storage", rationale: "Type 1 farms commonly use shared datastores; that is why the path matters." },
      { id: "d", text: "The guests were actually containers sharing a kernel panic", rationale: "The stem is a datastore path failure, not a shared-kernel container crash." },
    ],
    correct: "b",
    explanation: "Datastore/SAN loss takes every VM on that datastore with it.",
    remediationLessonId: "C1-D4-O1-L2",
    tags: ["misconception", "scenario"],
  }),
  q({
    id: "C1-D4-O1-TYPE1-Q006",
    objectiveId: "C1-D4-O1",
    conceptIds: ["C1-D4-O1-TYPE1"],
    difficulty: "exam",
    type: "scenario",
    scenario: "An admin manages ESXi through a browser from a jump box. There is no Windows desktop installed on the hypervisor host itself.",
    stem: "This architecture is BEST described as:",
    choices: [
      { id: "a", text: "Type 2, because a browser is an application", rationale: "The browser is on the jump box, not a hosted hypervisor on the server." },
      { id: "b", text: "Type 1, managed remotely", rationale: "Correct." },
      { id: "c", text: "SaaS, because a browser is involved", rationale: "A management UI in a browser is not SaaS by itself." },
      { id: "d", text: "PaaS, because ESXi is a platform for code push", rationale: "ESXi is a hypervisor, not an app runtime for developers." },
    ],
    correct: "b",
    explanation: "Bare-metal hypervisor plus remote console is the Type 1 operational picture.",
    remediationLessonId: "C1-D4-O1-L2",
  }),
  q({
    id: "C1-D4-O1-TYPE1-Q007",
    objectiveId: "C1-D4-O1",
    conceptIds: ["C1-D4-O1-TYPE1"],
    stem: "Why do Type 1 hosts often have several physical NICs?",
    choices: [
      { id: "a", text: "To separate management, VM traffic, migration, and storage", rationale: "Correct at A+ depth." },
      { id: "b", text: "Type 1 cannot bond or VLAN a single NIC", rationale: "It can; multiple NICs are for isolation and bandwidth, not inability." },
      { id: "c", text: "Each guest requires a dedicated physical NIC by law", rationale: "Virtual NICs share physical uplinks." },
      { id: "d", text: "Extra NICs disable VT-x", rationale: "Unrelated." },
    ],
    correct: "a",
    explanation: "Splitting management, VM, storage, and live-migration traffic is standard Type 1 design.",
    remediationLessonId: "C1-D4-O1-L2",
  }),
  q({
    id: "C1-D4-O1-TYPE1-Q008",
    objectiveId: "C1-D4-O1",
    conceptIds: ["C1-D4-O1-TYPE1"],
    stem: "Which product example is a Type 1 hypervisor in the datacenter sense?",
    choices: [
      { id: "a", text: "Oracle VirtualBox on a Windows laptop", rationale: "VirtualBox is a Type 2 (hosted) product sitting on a desktop OS." },
      { id: "b", text: "VMware ESXi on a rack server", rationale: "Correct. ESXi is the classic bare-metal Type 1 example." },
      { id: "c", text: "Docker Desktop sharing the host kernel only", rationale: "That is a container engine sharing a kernel, not a Type 1 hypervisor." },
      { id: "d", text: "Microsoft 365 in a browser", rationale: "That is SaaS — an application service, not a hypervisor." },
    ],
    correct: "b",
    explanation: "ESXi is the classic bare-metal example used in A+ teaching.",
    remediationLessonId: "C1-D4-O1-L2",
    tags: ["terminology"],
  }),
  q({
    id: "C1-D4-O1-TYPE2-Q001",
    objectiveId: "C1-D4-O1",
    conceptIds: ["C1-D4-O1-TYPE2"],
    difficulty: "intro",
    stem: "A help-desk technician installs VMware Workstation on a Windows 11 laptop to run a Linux guest. Which hypervisor type is this?",
    choices: [
      { id: "a", text: "Type 1", rationale: "Type 1 sits on the metal, not as an app on Windows 11." },
      { id: "b", text: "Type 2", rationale: "Correct. Hosted on a general-purpose OS." },
      { id: "c", text: "Type 0 firmware", rationale: "Not an A+ class." },
      { id: "d", text: "Community cloud", rationale: "A local app is not a cloud deployment model." },
    ],
    correct: "b",
    explanation: "Workstation/VirtualBox-class products are Type 2 (hosted) hypervisors.",
    remediationLessonId: "C1-D4-O1-L2",
  }),
  q({
    id: "C1-D4-O1-TYPE2-Q002",
    objectiveId: "C1-D4-O1",
    conceptIds: ["C1-D4-O1-TYPE2"],
    type: "scenario",
    scenario: "A Type 2 guest is sluggish. Host Task Manager shows 95% RAM used by Chrome plus the hypervisor process. The laptop is on a power-saver plan.",
    stem: "What should the technician do FIRST?",
    choices: [
      { id: "a", text: "Replace the laptop motherboard", rationale: "No evidence of a dead board." },
      { id: "b", text: "Check host RAM pressure and power plan before adding vCPUs", rationale: "Correct. Type 2 shares RAM and CPU with the host OS." },
      { id: "c", text: "Convert the guest to RAID 0", rationale: "RAID is storage arrays, not a VM speed knob here." },
      { id: "d", text: "Disable VT-x to force software emulation for accuracy", rationale: "Emulation would make it slower." },
    ],
    correct: "b",
    explanation: "Type 2 performance is host RAM, host CPU, and often laptop power policy.",
    remediationLessonId: "C1-D4-O1-L2",
    tags: ["FIRST"],
  }),
  q({
    id: "C1-D4-O1-TYPE2-Q003",
    objectiveId: "C1-D4-O1",
    conceptIds: ["C1-D4-O1-TYPE2"],
    stem: "A user on Windows 11 Home cannot enable Hyper-V. What is the MOST likely reason?",
    choices: [
      { id: "a", text: "Home edition does not include client Hyper-V", rationale: "Correct. Client Hyper-V ships with Pro/Enterprise/Education, not Home." },
      { id: "b", text: "Type 2 products never run on laptops", rationale: "Workstation/VirtualBox-class Type 2 products are built for laptops." },
      { id: "c", text: "ESXi is already hiding under Home", rationale: "Windows Home does not secretly run ESXi under the desktop." },
      { id: "d", text: "Containers block all hypervisors", rationale: "Container engines do not remove Hyper-V edition licensing." },
    ],
    correct: "a",
    explanation: "Client Hyper-V is a Pro/Enterprise/Education feature, not Home.",
    remediationLessonId: "C1-D4-O1-L2",
    tags: ["misconception"],
  }),
  q({
    id: "C1-D4-O1-TYPE2-Q004",
    objectiveId: "C1-D4-O1",
    conceptIds: ["C1-D4-O1-TYPE2"],
    stem: "If the host OS on a Type 2 workstation hangs, what happens to the guests?",
    choices: [
      { id: "a", text: "Guests keep running on the metal independently", rationale: "That would be Type 1." },
      { id: "b", text: "Guests hang with the host OS", rationale: "Correct. They depend on the hosted stack." },
      { id: "c", text: "Guests automatically fail over to Azure", rationale: "Not unless you built that." },
      { id: "d", text: "Only NAT guests hang; bridged guests continue", rationale: "The hypervisor process is still on the hung OS." },
    ],
    correct: "b",
    explanation: "Type 2 guests live and die with the host operating system.",
    remediationLessonId: "C1-D4-O1-L2",
  }),
  q({
    id: "C1-D4-O1-TYPE2-Q005",
    objectiveId: "C1-D4-O1",
    conceptIds: ["C1-D4-O1-TYPE2"],
    type: "multi",
    stem: "Which TWO clues on a stem point to Type 2 rather than Type 1? (Choose two.)",
    choices: [
      { id: "a", text: "Installed as an application beside Outlook", rationale: "Correct. Hosted." },
      { id: "b", text: "Laptop lab for a single Linux guest", rationale: "Correct. Typical Type 2 use case." },
      { id: "c", text: "Bare-metal install with no local desktop OS", rationale: "Type 1." },
      { id: "d", text: "Forty VDI sessions on a rack host", rationale: "Type 1." },
      { id: "e", text: "Management only via a datacenter fabric", rationale: "Type 1 flavor." },
    ],
    correct: ["a", "b"],
    explanation: "Application-on-OS plus workstation lab is Type 2.",
    remediationLessonId: "C1-D4-O1-L2",
    tags: ["multi"],
  }),
  q({
    id: "C1-D4-O1-TYPE2-Q006",
    objectiveId: "C1-D4-O1",
    conceptIds: ["C1-D4-O1-TYPE2"],
    stem: "A 64-bit guest will not start in VirtualBox until the technician enables virtualization in UEFI. Why?",
    choices: [
      { id: "a", text: "Without VT-x/AMD-V the product cannot efficiently virtualize 64-bit guests", rationale: "Correct. Enable VT-x/AMD-V in UEFI; do not 'fix' it by adding vCPUs." },
      { id: "b", text: "UEFI virtualization disables RAM so guests must be 32-bit", rationale: "Virtualization extensions do not shrink RAM or force 32-bit guests." },
      { id: "c", text: "Type 2 never uses CPU extensions", rationale: "Type 2 still needs VT-x/AMD-V for modern 64-bit guests." },
      { id: "d", text: "The guest is actually SaaS and needs a license key in firmware", rationale: "SaaS is a cloud service model; it is not why a local guest fails to start." },
    ],
    correct: "a",
    explanation: "Hosted hypervisors still require hardware virtualization extensions for modern guests.",
    remediationLessonId: "C1-D4-O1-L2",
    tags: ["FIRST"],
  }),
  q({
    id: "C1-D4-O1-TYPE2-Q007",
    objectiveId: "C1-D4-O1",
    conceptIds: ["C1-D4-O1-TYPE2"],
    stem: "Which statement is a common misconception about Type 2?",
    choices: [
      { id: "a", text: "If a guest feels fast, the product must be Type 1", rationale: "Correct — speed does not define type. Type is where the hypervisor sits." },
      { id: "b", text: "Type 2 sits on a host OS", rationale: "True, not a misconception." },
      { id: "c", text: "Type 2 is common on technician laptops", rationale: "True." },
      { id: "d", text: "Host sleep can suspend Type 2 guests", rationale: "True and painful, not a misconception." },
    ],
    correct: "a",
    explanation: "Architecture (bare metal vs hosted), not snappiness, is the Type 1/Type 2 test.",
    remediationLessonId: "C1-D4-O1-L2",
    tags: ["misconception"],
  }),
  q({
    id: "C1-D4-O1-TYPE2-Q008",
    objectiveId: "C1-D4-O1",
    conceptIds: ["C1-D4-O1-TYPE2"],
    stem: "A tester needs Windows and Linux GUI desktops on one laptop this afternoon. BEST choice?",
    choices: [
      { id: "a", text: "Type 2 hypervisor and a guest OS image", rationale: "Correct for a laptop lab." },
      { id: "b", text: "Bare-metal ESXi wiping the laptop OS", rationale: "Destroys the technician's daily driver for a lab." },
      { id: "c", text: "A community cloud contract", rationale: "Too heavy and slow for this afternoon." },
      { id: "d", text: "RAID 1 across the two operating systems", rationale: "RAID is not dual-boot virtualization." },
    ],
    correct: "a",
    explanation: "Cross-platform laptop work is the Type 2 use case.",
    remediationLessonId: "C1-D4-O1-L2",
  }),
  q({
    id: "C1-D4-O1-VDI-Q001",
    objectiveId: "C1-D4-O1",
    conceptIds: ["C1-D4-O1-VDI"],
    difficulty: "intro",
    stem: "What is Virtual Desktop Infrastructure (VDI)?",
    choices: [
      { id: "a", text: "A desktop OS that runs in the datacenter while the user sees a remote session", rationale: "Correct. Pixels travel to the endpoint; the desktop VM stays near the servers." },
      { id: "b", text: "A Type 2 hypervisor that can only run one guest", rationale: "VDI is a desktop delivery farm, usually on Type 1 — not a one-guest Type 2 limit." },
      { id: "c", text: "SaaS email", rationale: "SaaS is an application you use in a browser; VDI is a full remote desktop OS." },
      { id: "d", text: "A container that shares the user's laptop kernel", rationale: "Containers share a host kernel for apps — that is not a remote desktop VM farm." },
    ],
    correct: "a",
    explanation: "VDI hosts the desktop centrally; the endpoint is a display and input path.",
    remediationLessonId: "C1-D4-O1-L3",
    tags: ["terminology"],
  }),
  q({
    id: "C1-D4-O1-VDI-Q002",
    objectiveId: "C1-D4-O1",
    conceptIds: ["C1-D4-O1-VDI"],
    type: "scenario",
    scenario: "Nurses at thin clients say 'the computer is frozen.' The thin clients ping. The connection broker is up. WAN latency to the VDI farm jumped to 400 ms with packet loss after a WAN change.",
    stem: "What should the technician investigate NEXT?",
    choices: [
      { id: "a", text: "Reimage every thin client local disk", rationale: "Thin clients may not hold the desktop disk; latency is the clue." },
      { id: "b", text: "The WAN path (latency and loss) affecting the display protocol", rationale: "Correct. VDI is network-sensitive." },
      { id: "c", text: "Replace CMOS batteries in the thin clients", rationale: "Clock batteries do not freeze a remote desktop session." },
      { id: "d", text: "Convert VDI to RAID 0 for speed", rationale: "Unrelated and dangerous." },
    ],
    correct: "b",
    explanation: "VDI sessions die on latency and loss even when the endpoint is 'up.'",
    remediationLessonId: "C1-D4-O1-L3",
    tags: ["NEXT"],
  }),
  q({
    id: "C1-D4-O1-VDI-Q003",
    objectiveId: "C1-D4-O1",
    conceptIds: ["C1-D4-O1-VDI"],
    stem: "Users on a non-persistent VDI pool lose Desktop files every night. What is the MOST likely explanation?",
    choices: [
      { id: "a", text: "The pool resets to a golden image at logoff, so local desktop files are discarded", rationale: "Correct." },
      { id: "b", text: "Thin clients always format themselves at 02:00", rationale: "Not a design." },
      { id: "c", text: "Type 2 snapshots expire nightly by ISO standard", rationale: "Invented rule." },
      { id: "d", text: "SaaS deleted the Windows profile because of metering", rationale: "This is VDI persistence, not SaaS metering." },
    ],
    correct: "a",
    explanation: "Non-persistent VDI requires profile disks or network shares for user files.",
    remediationLessonId: "C1-D4-O1-L3",
  }),
  q({
    id: "C1-D4-O1-VDI-Q004",
    objectiveId: "C1-D4-O1",
    conceptIds: ["C1-D4-O1-VDI"],
    stem: "How does VDI differ from RDP to a single tower under a desk?",
    choices: [
      { id: "a", text: "VDI is a managed farm of desktop VMs; RDP to a tower is remote access to one PC", rationale: "Correct." },
      { id: "b", text: "They are identical terms", rationale: "They are not." },
      { id: "c", text: "VDI cannot use a display protocol", rationale: "It must." },
      { id: "d", text: "RDP farms always run on Type 2 laptop hypervisors", rationale: "Backwards." },
    ],
    correct: "a",
    explanation: "VDI is infrastructure. One RDP session to a physical PC is not a VDI farm.",
    remediationLessonId: "C1-D4-O1-L3",
  }),
  q({
    id: "C1-D4-O1-VDI-Q005",
    objectiveId: "C1-D4-O1",
    conceptIds: ["C1-D4-O1-VDI"],
    stem: "A stolen VDI thin client is returned. Why is this often less of a data-loss event than a stolen laptop with a local disk?",
    choices: [
      { id: "a", text: "The desktop disk and data live in the datacenter, not on the thin client", rationale: "Correct — if the design is honest." },
      { id: "b", text: "Thin clients cannot be stolen", rationale: "They can." },
      { id: "c", text: "VDI encrypts the thief's house automatically", rationale: "Fantasy." },
      { id: "d", text: "Thin clients store every mailbox offline by default", rationale: "That would increase data-loss risk." },
    ],
    correct: "a",
    explanation: "Centralized data is a listed reason organizations buy VDI.",
    remediationLessonId: "C1-D4-O1-L3",
  }),
  q({
    id: "C1-D4-O1-VDI-Q006",
    objectiveId: "C1-D4-O1",
    conceptIds: ["C1-D4-O1-VDI"],
    difficulty: "exam",
    type: "scenario",
    scenario: "At 09:00 every weekday the VDI farm is slow. At 21:00 it is fine. Host CPU and RAM charts show a logon storm.",
    stem: "Which requirement is MOST implicated?",
    choices: [
      { id: "a", text: "Capacity at peak logon — Type 1 host resources and boot storms", rationale: "Correct." },
      { id: "b", text: "CMOS batteries in the thin clients", rationale: "Not time-of-day host CPU." },
      { id: "c", text: "Containers sharing a kernel on each thin client", rationale: "Wrong product." },
      { id: "d", text: "APIPA on the SAN", rationale: "SAN addressing is not APIPA, and the chart is host CPU." },
    ],
    correct: "a",
    explanation: "VDI must be sized for the morning logon storm, not for midnight idle.",
    remediationLessonId: "C1-D4-O1-L3",
  }),
  q({
    id: "C1-D4-O1-VDI-Q007",
    objectiveId: "C1-D4-O1",
    conceptIds: ["C1-D4-O1-VDI"],
    stem: "Which security requirement is a reason to choose VDI for contractors?",
    choices: [
      { id: "a", text: "Data stays in the datacenter; the endpoint can be locked down", rationale: "Correct." },
      { id: "b", text: "VDI disables all authentication", rationale: "The opposite of a security requirement." },
      { id: "c", text: "Contractors must use Type 2 on USB sticks", rationale: "Not VDI." },
      { id: "d", text: "VDI requires every contractor to take the host hypervisor home", rationale: "Dangerous and not the model." },
    ],
    correct: "a",
    explanation: "Kiosk/contractor VDI keeps the desktop and data off the untrusted endpoint.",
    remediationLessonId: "C1-D4-O1-L3",
  }),
  q({
    id: "C1-D4-O1-VDI-Q008",
    objectiveId: "C1-D4-O1",
    conceptIds: ["C1-D4-O1-VDI"],
    stem: "VDI is NOT the same as which of the following?",
    choices: [
      { id: "a", text: "A farm of desktop VMs delivered by a broker", rationale: "That is VDI." },
      { id: "b", text: "SaaS, where the vendor hosts an application without giving you a desktop OS to patch", rationale: "Correct distinction." },
      { id: "c", text: "Persistent desktops that keep a user's VM", rationale: "That is a VDI persistence mode." },
      { id: "d", text: "Non-persistent pools that reset to a golden image", rationale: "Also VDI." },
    ],
    correct: "b",
    explanation: "SaaS is an app. VDI is a desktop OS session hosted centrally.",
    remediationLessonId: "C1-D4-O1-L3",
    tags: ["misconception"],
  }),
  q({
    id: "C1-D4-O1-CONTAINER-Q001",
    objectiveId: "C1-D4-O1",
    conceptIds: ["C1-D4-O1-CONTAINER"],
    difficulty: "intro",
    stem: "How does a container differ from a virtual machine?",
    choices: [
      { id: "a", text: "A container shares the host kernel; a VM has its own guest OS/kernel", rationale: "Correct." },
      { id: "b", text: "A container always includes a full Windows kernel", rationale: "Containers share the host kernel family." },
      { id: "c", text: "A VM cannot isolate an application", rationale: "VMs isolate whole machines." },
      { id: "d", text: "Containers require Type 1 and VMs require Type 2", rationale: "Both can run on either; the isolation model is the difference." },
    ],
    correct: "a",
    explanation: "OS-level isolation versus hardware virtualization is the exam distinction.",
    remediationLessonId: "C1-D4-O1-L3",
  }),
  q({
    id: "C1-D4-O1-CONTAINER-Q002",
    objectiveId: "C1-D4-O1",
    conceptIds: ["C1-D4-O1-CONTAINER"],
    stem: "A stem says 'lightweight microservices that start in seconds and share the host OS.' Which technology fits BEST?",
    choices: [
      { id: "a", text: "Containers", rationale: "Correct." },
      { id: "b", text: "Full VMs with separate kernels", rationale: "Heavier, slower start." },
      { id: "c", text: "VDI thin clients", rationale: "Human desktops, not microservices." },
      { id: "d", text: "Type 1 only, with no OS", rationale: "Type 1 still runs guest OSes for VMs." },
    ],
    correct: "a",
    explanation: "Density and fast start on a shared kernel is the container story.",
    remediationLessonId: "C1-D4-O1-L3",
  }),
  q({
    id: "C1-D4-O1-CONTAINER-Q003",
    objectiveId: "C1-D4-O1",
    conceptIds: ["C1-D4-O1-CONTAINER"],
    type: "scenario",
    scenario: "A tester needs to run Windows 11 and Ubuntu with separate kernels on one workstation for driver work.",
    stem: "Which is the BETTER isolation tool?",
    choices: [
      { id: "a", text: "A Linux container on Windows, because containers can change kernels", rationale: "They cannot; they share the host kernel family." },
      { id: "b", text: "Virtual machines", rationale: "Correct. Different kernels need VMs." },
      { id: "c", text: "SaaS only", rationale: "SaaS will not give you two kernels to test drivers." },
      { id: "d", text: "APIPA", rationale: "Link-local addressing is not isolation for OSes." },
    ],
    correct: "b",
    explanation: "Different operating systems/kernels are a VM requirement, not a container feature.",
    remediationLessonId: "C1-D4-O1-L3",
  }),
  q({
    id: "C1-D4-O1-CONTAINER-Q004",
    objectiveId: "C1-D4-O1",
    conceptIds: ["C1-D4-O1-CONTAINER"],
    stem: "A host kernel panic occurs on a box running 50 containers. What happens?",
    choices: [
      { id: "a", text: "Only one container dies; others have their own kernels", rationale: "They share the kernel." },
      { id: "b", text: "All containers on that host fail with the kernel", rationale: "Correct. Shared failure domain." },
      { id: "c", text: "The panic converts them into VMs automatically", rationale: "It does not." },
      { id: "d", text: "VDI brokers absorb the panic", rationale: "Unrelated." },
    ],
    correct: "b",
    explanation: "Shared kernel means a host kernel failure is every container on that host.",
    remediationLessonId: "C1-D4-O1-L3",
  }),
  q({
    id: "C1-D4-O1-CONTAINER-Q005",
    objectiveId: "C1-D4-O1",
    conceptIds: ["C1-D4-O1-CONTAINER"],
    stem: "Why are containers not 'more secure by default' than VMs?",
    choices: [
      { id: "a", text: "A breakout of the engine can be a breakout to the shared host kernel", rationale: "Correct." },
      { id: "b", text: "Containers cannot run on patched hosts", rationale: "They should." },
      { id: "c", text: "VMs cannot be isolated", rationale: "VMs are the stronger hardware boundary." },
      { id: "d", text: "Containers encrypt the hypervisor so VMs cannot start", rationale: "Invented." },
    ],
    correct: "a",
    explanation: "You still patch the host, scan images, and avoid privileged containers for untrusted work.",
    remediationLessonId: "C1-D4-O1-L3",
    tags: ["misconception"],
  }),
  q({
    id: "C1-D4-O1-CONTAINER-Q006",
    objectiveId: "C1-D4-O1",
    conceptIds: ["C1-D4-O1-CONTAINER"],
    type: "multi",
    stem: "Which TWO are appropriate container use cases at A+ depth? (Choose two.)",
    choices: [
      { id: "a", text: "Many copies of the same microservice on one patched host", rationale: "Correct." },
      { id: "b", text: "Fast start of an app with its libraries packaged", rationale: "Correct." },
      { id: "c", text: "Running a completely different kernel for a malware lab", rationale: "That is a VM job." },
      { id: "d", text: "Replacing a Type 1 host so hardware does not exist", rationale: "Containers still need a host OS/kernel." },
      { id: "e", text: "Non-persistent VDI golden images for nurses", rationale: "VDI, not containers." },
    ],
    correct: ["a", "b"],
    explanation: "Density and packaged apps are containers. Different kernels and hard malware isolation are VMs.",
    remediationLessonId: "C1-D4-O1-L3",
    tags: ["multi"],
  }),
  q({
    id: "C1-D4-O1-CONTAINER-Q007",
    objectiveId: "C1-D4-O1",
    conceptIds: ["C1-D4-O1-CONTAINER"],
    difficulty: "exam",
    stem: "A developer says a service 'works in Docker' but the published port is not listening on the host. Which check is MOST relevant?",
    choices: [
      { id: "a", text: "Whether the container published the port and the engine is running on that host", rationale: "Correct technician check." },
      { id: "b", text: "Whether RAID 6 is degraded", rationale: "Unrelated unless the datastore is actually dead." },
      { id: "c", text: "Whether the laptop is Type 1", rationale: "Docker on a laptop is not Type 1 architecture." },
      { id: "d", text: "Whether SaaS metering is prepaid", rationale: "Local Docker is not a SaaS invoice." },
    ],
    correct: "a",
    explanation: "Container tickets are image, engine, and published ports — not hypervisor type trivia.",
    remediationLessonId: "C1-D4-O1-L3",
  }),
  q({
    id: "C1-D4-O1-CONTAINER-Q008",
    objectiveId: "C1-D4-O1",
    conceptIds: ["C1-D4-O1-CONTAINER"],
    stem: "Which security practice applies to container images?",
    choices: [
      { id: "a", text: "Do not bake secrets into image layers; scan and patch the host", rationale: "Correct." },
      { id: "b", text: "Run everything as --privileged so isolation is stronger", rationale: "Privileged weakens isolation." },
      { id: "c", text: "Never patch the host because the image is the OS", rationale: "The host kernel is shared and must be patched." },
      { id: "d", text: "Store production passwords in the public registry README", rationale: "That is a leak." },
    ],
    correct: "a",
    explanation: "Images, registries, and the shared kernel are the container security surface.",
    remediationLessonId: "C1-D4-O1-L3",
  }),
  q({
    id: "C1-D4-O2-IAAS-Q001",
    objectiveId: "C1-D4-O2",
    conceptIds: ["C1-D4-O2-IAAS"],
    difficulty: "intro",
    stem: "In Infrastructure as a Service (IaaS), what do YOU typically still manage?",
    choices: [
      { id: "a", text: "The guest operating system, applications, and data", rationale: "Correct. IaaS hands you the stack from the OS up — patching Windows is still your job." },
      { id: "b", text: "The datacenter generators and cage cameras", rationale: "Facility physical security stays with the provider in public IaaS." },
      { id: "c", text: "The hypervisor firmware only, never the OS", rationale: "You do not patch the provider hypervisor; you do patch the guest OS." },
      { id: "d", text: "Nothing, because IaaS is the same as SaaS", rationale: "IaaS and SaaS differ by which layer you manage — they are not synonyms." },
    ],
    correct: "a",
    explanation: "IaaS rents VMs/networks/storage. You still patch the OS.",
    remediationLessonId: "C1-D4-O2-L2",
    tags: ["terminology"],
  }),
  q({
    id: "C1-D4-O2-IAAS-Q002",
    objectiveId: "C1-D4-O2",
    conceptIds: ["C1-D4-O2-IAAS"],
    type: "scenario",
    scenario: "A company needs a Windows Server they can domain-join and Group-Policy, hosted in a public cloud region.",
    stem: "Which service model fits BEST?",
    choices: [
      { id: "a", text: "SaaS", rationale: "SaaS would not give you a Windows Server to GPO." },
      { id: "b", text: "IaaS", rationale: "Correct. A VM you treat like a server." },
      { id: "c", text: "PaaS only, with no OS", rationale: "PaaS hides the OS." },
      { id: "d", text: "Community cloud as a service model", rationale: "Community is a deployment model, not IaaS/PaaS/SaaS." },
    ],
    correct: "b",
    explanation: "A Windows VM you patch and join is IaaS.",
    remediationLessonId: "C1-D4-O2-L2",
  }),
  q({
    id: "C1-D4-O2-IAAS-Q003",
    objectiveId: "C1-D4-O2",
    conceptIds: ["C1-D4-O2-IAAS"],
    stem: "An IaaS VM is reachable on RDP from the whole internet (0.0.0.0/0). Whose problem is that FIRST?",
    choices: [
      { id: "a", text: "The customer's network security groups / firewall on that VM", rationale: "Correct. Shared responsibility: you own the guest firewall." },
      { id: "b", text: "The provider's physical cameras", rationale: "Physical security does not open RDP." },
      { id: "c", text: "SaaS tenancy isolation", rationale: "This is IaaS." },
      { id: "d", text: "APIPA", rationale: "Unrelated." },
    ],
    correct: "a",
    explanation: "IaaS customers own guest OS and network filters they configured.",
    remediationLessonId: "C1-D4-O2-L2",
  }),
  q({
    id: "C1-D4-O2-IAAS-Q004",
    objectiveId: "C1-D4-O2",
    conceptIds: ["C1-D4-O2-IAAS"],
    stem: "Which example is IaaS?",
    choices: [
      { id: "a", text: "An Azure Virtual Machine or Amazon EC2 instance", rationale: "Correct." },
      { id: "b", text: "Microsoft 365 mail in a browser", rationale: "SaaS." },
      { id: "c", text: "Azure App Service where you only push code", rationale: "PaaS." },
      { id: "d", text: "A consumer photo gallery with no VM access", rationale: "SaaS-like." },
    ],
    correct: "a",
    explanation: "If you pick the image and RDP/SSH to a VM, it is IaaS.",
    remediationLessonId: "C1-D4-O2-L2",
  }),
  q({
    id: "C1-D4-O2-IAAS-Q005",
    objectiveId: "C1-D4-O2",
    conceptIds: ["C1-D4-O2-IAAS"],
    stem: "A test IaaS VM was left running over a three-day holiday. Finance asks about the bill. What concept explains the charge?",
    choices: [
      { id: "a", text: "Metered compute hours", rationale: "Correct." },
      { id: "b", text: "RAID 0 licensing", rationale: "Not a cloud invoice line." },
      { id: "c", text: "Type 2 beep codes", rationale: "Unrelated." },
      { id: "d", text: "Community cloud requires idle VMs to be free", rationale: "Idle IaaS still bills unless you stop/deallocate per the SKU." },
    ],
    correct: "a",
    explanation: "Cloud IaaS is measured service. Idle VMs still consume budget.",
    remediationLessonId: "C1-D4-O2-L3",
  }),
  q({
    id: "C1-D4-O2-IAAS-Q006",
    objectiveId: "C1-D4-O2",
    conceptIds: ["C1-D4-O2-IAAS"],
    stem: "Pulling a large backup from a cloud file share to an on-premises NAS is MOST associated with which metered surprise?",
    choices: [
      { id: "a", text: "Egress (data leaving the cloud)", rationale: "Correct." },
      { id: "b", text: "Ingress, which is usually the expensive direction", rationale: "Ingress is often cheap; egress is the trap." },
      { id: "c", text: "CMOS battery shipping", rationale: "Unrelated." },
      { id: "d", text: "Type 1 beep codes", rationale: "Unrelated." },
    ],
    correct: "a",
    explanation: "Egress GB is a classic metered cost. Design restores on purpose.",
    remediationLessonId: "C1-D4-O2-L3",
  }),
  q({
    id: "C1-D4-O2-IAAS-Q007",
    objectiveId: "C1-D4-O2",
    conceptIds: ["C1-D4-O2-IAAS"],
    difficulty: "exam",
    type: "scenario",
    scenario: "Windows Update fails on a cloud VM. The provider status page is green. You can RDP. The guest has no current patches.",
    stem: "Who is responsible for patching the OS?",
    choices: [
      { id: "a", text: "The customer (IaaS guest OS is in their scope)", rationale: "Correct." },
      { id: "b", text: "The provider, because all cloud OS patches are SaaS", rationale: "Not for IaaS." },
      { id: "c", text: "Nobody; cloud VMs cannot be patched", rationale: "They must be." },
      { id: "d", text: "The community cloud consortium only", rationale: "This is a standard IaaS VM." },
    ],
    correct: "a",
    explanation: "Shared responsibility: IaaS OS patches are yours.",
    remediationLessonId: "C1-D4-O2-L2",
  }),
  q({
    id: "C1-D4-O2-PAAS-Q001",
    objectiveId: "C1-D4-O2",
    conceptIds: ["C1-D4-O2-PAAS"],
    difficulty: "intro",
    stem: "Platform as a Service (PaaS) is BEST described as:",
    choices: [
      { id: "a", text: "You deploy the application; the provider manages OS and runtime", rationale: "Correct. PaaS is git-push / deploy — not RDP to patch Ubuntu." },
      { id: "b", text: "You patch Windows and install IIS yourself on a VM", rationale: "That is IaaS: you still own the guest OS." },
      { id: "c", text: "You only use a finished app in a browser and never deploy code", rationale: "That is SaaS — finished app, not a platform you deploy onto." },
      { id: "d", text: "You own the datacenter generators", rationale: "Owning the facility is on-premises, not a PaaS contract." },
    ],
    correct: "a",
    explanation: "PaaS is the middle of the stack: code in, OS out of your hands.",
    remediationLessonId: "C1-D4-O2-L2",
    tags: ["terminology"],
  }),
  q({
    id: "C1-D4-O2-PAAS-Q002",
    objectiveId: "C1-D4-O2",
    conceptIds: ["C1-D4-O2-PAAS"],
    stem: "Developers git-push a web app and never RDP to a server. Which model is that?",
    choices: [
      { id: "a", text: "PaaS", rationale: "Correct." },
      { id: "b", text: "IaaS", rationale: "IaaS would still look like a VM they manage." },
      { id: "c", text: "Type 2 hypervisor", rationale: "Not a cloud service model." },
      { id: "d", text: "RAID 10", rationale: "Storage, not PaaS." },
    ],
    correct: "a",
    explanation: "Push code, no OS management: PaaS.",
    remediationLessonId: "C1-D4-O2-L2",
  }),
  q({
    id: "C1-D4-O2-PAAS-Q003",
    objectiveId: "C1-D4-O2",
    conceptIds: ["C1-D4-O2-PAAS"],
    type: "scenario",
    scenario: "A ticket says the Python runtime on the platform changed and the app failed. There is no Windows VM to RDP into.",
    stem: "This ticket is MOST characteristic of:",
    choices: [
      { id: "a", text: "PaaS", rationale: "Correct. You own the app; they own the runtime." },
      { id: "b", text: "A local Type 2 snapshot", rationale: "Not a runtime platform." },
      { id: "c", text: "A CMOS failure", rationale: "No." },
      { id: "d", text: "APIPA", rationale: "No." },
    ],
    correct: "a",
    explanation: "Runtime/platform changes without a guest OS to patch are PaaS-shaped.",
    remediationLessonId: "C1-D4-O2-L2",
  }),
  q({
    id: "C1-D4-O2-PAAS-Q004",
    objectiveId: "C1-D4-O2",
    conceptIds: ["C1-D4-O2-PAAS"],
    stem: "Which offering is PaaS-like at A+ depth?",
    choices: [
      { id: "a", text: "A managed web app service or managed SQL database", rationale: "Correct." },
      { id: "b", text: "A raw VM with a public IP", rationale: "IaaS." },
      { id: "c", text: "Gmail for users", rationale: "SaaS." },
      { id: "d", text: "VMware Workstation", rationale: "Type 2 hypervisor." },
    ],
    correct: "a",
    explanation: "Managed runtimes and databases are the PaaS examples A+ expects.",
    remediationLessonId: "C1-D4-O2-L2",
  }),
  q({
    id: "C1-D4-O2-PAAS-Q005",
    objectiveId: "C1-D4-O2",
    conceptIds: ["C1-D4-O2-PAAS"],
    stem: "On PaaS, who typically patches the guest OS?",
    choices: [
      { id: "a", text: "The provider", rationale: "Correct." },
      { id: "b", text: "The help-desk technician via RDP every Tuesday", rationale: "You usually cannot RDP the platform OS." },
      { id: "c", text: "Each end user in the browser", rationale: "Users do not patch PaaS OS." },
      { id: "d", text: "Nobody; PaaS cannot have an OS", rationale: "There is an OS; you just do not manage it." },
    ],
    correct: "a",
    explanation: "PaaS moves OS patching to the provider. You still own app code and data.",
    remediationLessonId: "C1-D4-O2-L2",
  }),
  q({
    id: "C1-D4-O2-PAAS-Q006",
    objectiveId: "C1-D4-O2",
    conceptIds: ["C1-D4-O2-PAAS"],
    type: "multi",
    stem: "A company wants developers to deploy a web app without staffing Windows patching. Which TWO statements are true? (Choose two.)",
    choices: [
      { id: "a", text: "PaaS matches that staffing model", rationale: "Correct." },
      { id: "b", text: "They still classify and protect the data the app stores", rationale: "Correct. Data stays in customer scope." },
      { id: "c", text: "They must RDP to patch IIS weekly", rationale: "That is IaaS work they wanted to avoid." },
      { id: "d", text: "PaaS means the app cannot use a database", rationale: "Managed DBs are often PaaS too." },
      { id: "e", text: "This is Type 1 only and cannot be public cloud", rationale: "PaaS is commonly public cloud." },
    ],
    correct: ["a", "b"],
    explanation: "PaaS removes OS toil; it does not remove data responsibility.",
    remediationLessonId: "C1-D4-O2-L2",
    tags: ["multi"],
  }),
  q({
    id: "C1-D4-O2-PAAS-Q007",
    objectiveId: "C1-D4-O2",
    conceptIds: ["C1-D4-O2-PAAS"],
    stem: "Why is 'install a printer driver on the platform' usually the wrong PaaS ticket?",
    choices: [
      { id: "a", text: "You do not get a general-purpose desktop OS to install drivers into", rationale: "Correct." },
      { id: "b", text: "PaaS forbids all printing forever", rationale: "Overstated. You might call an API; you still do not load a desktop driver on the platform." },
      { id: "c", text: "Printers can only be IaaS", rationale: "Printers are devices; the model is about the app host." },
      { id: "d", text: "PaaS is only for Type 2 laptops", rationale: "No." },
    ],
    correct: "a",
    explanation: "If the stem needs a guest OS to install into, it is IaaS, not PaaS.",
    remediationLessonId: "C1-D4-O2-L2",
  }),
  q({
    id: "C1-D4-O2-SAAS-Q001",
    objectiveId: "C1-D4-O2",
    conceptIds: ["C1-D4-O2-SAAS"],
    difficulty: "intro",
    stem: "Software as a Service (SaaS) means:",
    choices: [
      { id: "a", text: "The provider runs the application; you use a client or browser and manage users/licenses", rationale: "Correct. SaaS tickets are licenses, MFA, and sharing — not IIS or hypervisors." },
      { id: "b", text: "You patch the hypervisor nightly", rationale: "Hypervisor patching is IaaS/on-prem virtualization, not SaaS." },
      { id: "c", text: "You deploy code onto a runtime you do not see", rationale: "Deploying your code onto a managed runtime is PaaS." },
      { id: "d", text: "You own the SAN in the provider region", rationale: "You do not own the provider SAN when you subscribe to SaaS." },
    ],
    correct: "a",
    explanation: "SaaS is the finished app. Help desk does licenses, MFA, sharing — not IIS.",
    remediationLessonId: "C1-D4-O2-L2",
    tags: ["terminology"],
  }),
  q({
    id: "C1-D4-O2-SAAS-Q002",
    objectiveId: "C1-D4-O2",
    conceptIds: ["C1-D4-O2-SAAS"],
    stem: "Microsoft 365 mail and docs for a company tenant is an example of:",
    choices: [
      { id: "a", text: "SaaS", rationale: "Correct." },
      { id: "b", text: "IaaS", rationale: "You do not RDP the Exchange VM." },
      { id: "c", text: "Type 1 only", rationale: "Service model, not hypervisor type." },
      { id: "d", text: "A private CMOS cloud", rationale: "Not a thing." },
    ],
    correct: "a",
    explanation: "Browser/client plus a license portal is the SaaS picture.",
    remediationLessonId: "C1-D4-O2-L2",
  }),
  q({
    id: "C1-D4-O2-SAAS-Q003",
    objectiveId: "C1-D4-O2",
    conceptIds: ["C1-D4-O2-SAAS"],
    type: "scenario",
    scenario: "A sharing link was set to 'anyone with the link' and a spreadsheet of salaries leaked. The provider status page is green.",
    stem: "What is the BEST classification of this failure?",
    choices: [
      { id: "a", text: "Customer tenant configuration (SaaS shared responsibility)", rationale: "Correct." },
      { id: "b", text: "Provider hypervisor crash", rationale: "Status is green; this is a sharing setting." },
      { id: "c", text: "APIPA on the SaaS leaf switch", rationale: "Not how SaaS tenancy works for this ticket." },
      { id: "d", text: "Need to RDP the SaaS VM and run chkdsk", rationale: "There is no customer VM." },
    ],
    correct: "a",
    explanation: "SaaS customers own sharing, identity, and data classification.",
    remediationLessonId: "C1-D4-O2-L3",
  }),
  q({
    id: "C1-D4-O2-SAAS-Q004",
    objectiveId: "C1-D4-O2",
    conceptIds: ["C1-D4-O2-SAAS"],
    stem: "A user says OneDrive 'deleted' a file after they deleted it on their laptop. Version history still has it. What concept is in play?",
    choices: [
      { id: "a", text: "File synchronization replicates the delete; versioning is the undo", rationale: "Correct. Sync is not a backup by itself." },
      { id: "b", text: "The region lost availability", rationale: "Version history existing contradicts an outage wipe." },
      { id: "c", text: "IaaS snapshot of the laptop", rationale: "Wrong layer." },
      { id: "d", text: "Type 2 host-only networking", rationale: "Unrelated." },
    ],
    correct: "a",
    explanation: "Sync copies deletes. Recycle bin/version history is the help-desk move.",
    remediationLessonId: "C1-D4-O2-L1",
  }),
  q({
    id: "C1-D4-O2-SAAS-Q005",
    objectiveId: "C1-D4-O2",
    conceptIds: ["C1-D4-O2-SAAS"],
    stem: "Which help-desk task is characteristic of SaaS rather than IaaS?",
    choices: [
      { id: "a", text: "Assigning a license and resetting MFA on a mailbox", rationale: "Correct." },
      { id: "b", text: "Extending a VHDX and installing Windows updates on a VM", rationale: "IaaS." },
      { id: "c", text: "Enabling VT-x in UEFI", rationale: "Local firmware." },
      { id: "d", text: "Rebuilding RAID 5", rationale: "Storage hardware." },
    ],
    correct: "a",
    explanation: "Identity and licenses are the SaaS technician's daily work.",
    remediationLessonId: "C1-D4-O2-L2",
  }),
  q({
    id: "C1-D4-O2-SAAS-Q006",
    objectiveId: "C1-D4-O2",
    conceptIds: ["C1-D4-O2-SAAS"],
    difficulty: "exam",
    stem: "A manager wants 'email without Exchange servers to patch.' BEST model?",
    choices: [
      { id: "a", text: "SaaS mailbox", rationale: "Correct." },
      { id: "b", text: "IaaS VM they still patch", rationale: "They would still patch Exchange." },
      { id: "c", text: "Type 2 on each laptop running Exchange", rationale: "Worse." },
      { id: "d", text: "Community CMOS", rationale: "Not a model." },
    ],
    correct: "a",
    explanation: "Stop managing the app stack: SaaS.",
    remediationLessonId: "C1-D4-O2-L2",
  }),
  q({
    id: "C1-D4-O2-SAAS-Q007",
    objectiveId: "C1-D4-O2",
    conceptIds: ["C1-D4-O2-SAAS"],
    stem: "SaaS elasticity is usually:",
    choices: [
      { id: "a", text: "Invisible to the customer; the vendor scales the app", rationale: "Correct." },
      { id: "b", text: "The customer adding vCPUs in the hypervisor UI every morning", rationale: "That is IaaS scale-up work." },
      { id: "c", text: "Impossible", rationale: "Vendors scale constantly." },
      { id: "d", text: "Only possible on Type 2", rationale: "Service model ≠ hypervisor type." },
    ],
    correct: "a",
    explanation: "You feel SaaS capacity as 'it works at 09:00,' not as a vCPU slider.",
    remediationLessonId: "C1-D4-O2-L3",
  }),
  q({
    id: "C1-D4-O2-HYBRID-Q001",
    objectiveId: "C1-D4-O2",
    conceptIds: ["C1-D4-O2-HYBRID"],
    difficulty: "intro",
    stem: "Which description is a hybrid cloud?",
    choices: [
      { id: "a", text: "On-premises identity/data connected to public-cloud workloads over a controlled path", rationale: "Correct. Hybrid is a design with a path you can break — tunnel, DC, or cloud IdP." },
      { id: "b", text: "Only a public provider, no private systems", rationale: "That is public cloud alone, not hybrid." },
      { id: "c", text: "One unused tower in a closet", rationale: "A dusty tower is not a cloud deployment model." },
      { id: "d", text: "SaaS that cannot use a VPN", rationale: "SaaS can sit in a hybrid design; forbidding VPN is not the hybrid definition." },
    ],
    correct: "a",
    explanation: "Hybrid spans private and public with a real network path.",
    remediationLessonId: "C1-D4-O2-L1",
    tags: ["terminology"],
  }),
  q({
    id: "C1-D4-O2-HYBRID-Q002",
    objectiveId: "C1-D4-O2",
    conceptIds: ["C1-D4-O2-HYBRID"],
    type: "scenario",
    scenario: "Users cannot sign in to a cloud app that authenticates against an on-premises domain controller via VPN. The cloud status page is green. The VPN tunnel is down.",
    stem: "What should the technician do NEXT?",
    choices: [
      { id: "a", text: "Investigate the hybrid path (VPN/identity), not 'Azure is down'", rationale: "Correct." },
      { id: "b", text: "Replace CMOS batteries in the cloud region", rationale: "Not a thing you do." },
      { id: "c", text: "Convert the company to RAID 0", rationale: "Unrelated." },
      { id: "d", text: "Tell users to enable APIPA", rationale: "APIPA will not fix identity VPN." },
    ],
    correct: "a",
    explanation: "Hybrid outages are often the tunnel or the on-prem DC, not the public region.",
    remediationLessonId: "C1-D4-O2-L1",
    tags: ["NEXT"],
  }),
  q({
    id: "C1-D4-O2-HYBRID-Q003",
    objectiveId: "C1-D4-O2",
    conceptIds: ["C1-D4-O2-HYBRID"],
    stem: "A private cloud is BEST distinguished from 'we have one ESXi host' by:",
    choices: [
      { id: "a", text: "Cloud-style pooling, metering, and self-service on dedicated infrastructure", rationale: "Correct." },
      { id: "b", text: "The host being painted blue", rationale: "Not a criterion." },
      { id: "c", text: "Virtual machines being illegal in private datacenters", rationale: "False." },
      { id: "d", text: "Private cloud meaning the data is on the public internet unauthenticated", rationale: "Opposite of the word private." },
    ],
    correct: "a",
    explanation: "Private cloud is a capability model, not merely 'a VM exists.'",
    remediationLessonId: "C1-D4-O2-L1",
  }),
  q({
    id: "C1-D4-O2-HYBRID-Q004",
    objectiveId: "C1-D4-O2",
    conceptIds: ["C1-D4-O2-HYBRID"],
    stem: "Several hospitals in a region share a platform built for the same compliance community. Which deployment model is that?",
    choices: [
      { id: "a", text: "Community cloud", rationale: "Correct." },
      { id: "b", text: "A Type 2 hypervisor", rationale: "Wrong category." },
      { id: "c", text: "SaaS as a deployment model", rationale: "SaaS is a service model." },
      { id: "d", text: "APIPA cloud", rationale: "Not a model." },
    ],
    correct: "a",
    explanation: "Community cloud is shared by a defined set of orgs with a common mission.",
    remediationLessonId: "C1-D4-O2-L1",
  }),
  q({
    id: "C1-D4-O2-HYBRID-Q005",
    objectiveId: "C1-D4-O2",
    conceptIds: ["C1-D4-O2-HYBRID"],
    stem: "Public cloud means:",
    choices: [
      { id: "a", text: "Provider-owned infrastructure shared by many customers; data is not automatically public", rationale: "Correct." },
      { id: "b", text: "Anyone on the internet can read your disks without auth", rationale: "That would be a misconfiguration, not the definition." },
      { id: "c", text: "You badge into the cage weekly", rationale: "You typically cannot." },
      { id: "d", text: "There is no metering", rationale: "Public cloud is measured." },
    ],
    correct: "a",
    explanation: "Public refers to the shared provider platform, not 'unauthenticated data.'",
    remediationLessonId: "C1-D4-O2-L1",
    tags: ["misconception"],
  }),
  q({
    id: "C1-D4-O2-HYBRID-Q006",
    objectiveId: "C1-D4-O2",
    conceptIds: ["C1-D4-O2-HYBRID"],
    type: "multi",
    stem: "Which TWO are deployment models rather than service models? (Choose two.)",
    choices: [
      { id: "a", text: "Hybrid", rationale: "Correct. Where/with whom." },
      { id: "b", text: "Public", rationale: "Correct." },
      { id: "c", text: "IaaS", rationale: "Service model." },
      { id: "d", text: "SaaS", rationale: "Service model." },
      { id: "e", text: "PaaS", rationale: "Service model." },
    ],
    correct: ["a", "b"],
    explanation: "Public/private/hybrid/community are placement. IaaS/PaaS/SaaS are layers.",
    remediationLessonId: "C1-D4-O2-L1",
    tags: ["multi"],
  }),
  q({
    id: "C1-D4-O2-HYBRID-Q007",
    objectiveId: "C1-D4-O2",
    conceptIds: ["C1-D4-O2-HYBRID"],
    difficulty: "exam",
    stem: "A company keeps a sensitive database on-premises and bursts web VMs into a public cloud. Which term applies?",
    choices: [
      { id: "a", text: "Hybrid", rationale: "Correct." },
      { id: "b", text: "Only SaaS", rationale: "Web VMs are not SaaS by themselves." },
      { id: "c", text: "Type 2 mandatory", rationale: "Burst VMs in public cloud are typically Type 1 on the provider side." },
      { id: "d", text: "Community only, because two systems exist", rationale: "Two systems in one company is hybrid, not community." },
    ],
    correct: "a",
    explanation: "Split placement with a path is hybrid cloud.",
    remediationLessonId: "C1-D4-O2-L1",
  }),
  q({
    id: "C1-D4-O2-ELASTIC-Q001",
    objectiveId: "C1-D4-O2",
    conceptIds: ["C1-D4-O2-ELASTIC"],
    difficulty: "intro",
    stem: "Elasticity in cloud computing means:",
    choices: [
      { id: "a", text: "Capacity can increase and decrease with demand", rationale: "Correct. Elasticity is the up-and-down story — more at noon, fewer at night." },
      { id: "b", text: "You buy one huge server and never change it", rationale: "A fixed closet server is scale-once, not elastic." },
      { id: "c", text: "The provider never meters usage", rationale: "Cloud is usually metered; elasticity and metering often travel together." },
      { id: "d", text: "VMs cannot be turned off", rationale: "Idle capacity is often stopped or scaled in — that is part of elasticity." },
    ],
    correct: "a",
    explanation: "Elasticity is the up-and-down story, not merely 'big.'",
    remediationLessonId: "C1-D4-O2-L3",
    tags: ["misconception", "terminology"],
  }),
  q({
    id: "C1-D4-O2-ELASTIC-Q002",
    objectiveId: "C1-D4-O2",
    conceptIds: ["C1-D4-O2-ELASTIC"],
    stem: "Adding more web instances behind a load balancer at noon and removing them at night is:",
    choices: [
      { id: "a", text: "Scale-out (horizontal) elasticity", rationale: "Correct." },
      { id: "b", text: "Scale-up of a single box only", rationale: "Scale-up is a bigger SKU, not more instances." },
      { id: "c", text: "RAID striping", rationale: "Wrong domain." },
      { id: "d", text: "APIPA pooling", rationale: "Not a thing." },
    ],
    correct: "a",
    explanation: "More instances = scale out. Bigger instance = scale up.",
    remediationLessonId: "C1-D4-O2-L3",
  }),
  q({
    id: "C1-D4-O2-ELASTIC-Q003",
    objectiveId: "C1-D4-O2",
    conceptIds: ["C1-D4-O2-ELASTIC"],
    type: "scenario",
    scenario: "A retailer expects a 10× traffic spike on sale day. Waiting six weeks for a server shipment is not acceptable.",
    stem: "Which cloud trait is the BEST match?",
    choices: [
      { id: "a", text: "Rapid elasticity / on-demand capacity", rationale: "Correct." },
      { id: "b", text: "A single non-redundant IaaS VM with no backup", rationale: "That is hope, not elasticity." },
      { id: "c", text: "Disabling metering", rationale: "You will still pay for the spike." },
      { id: "d", text: "Type 2 on the CEO laptop", rationale: "Not a sale-day architecture." },
    ],
    correct: "a",
    explanation: "Cloud elasticity is capacity without a hardware purchase order.",
    remediationLessonId: "C1-D4-O2-L3",
  }),
  q({
    id: "C1-D4-O2-ELASTIC-Q004",
    objectiveId: "C1-D4-O2",
    conceptIds: ["C1-D4-O2-ELASTIC"],
    stem: "Giving one database VM a larger vCPU/RAM SKU is:",
    choices: [
      { id: "a", text: "Scale-up (vertical)", rationale: "Correct." },
      { id: "b", text: "Scale-out", rationale: "Scale-out would add more instances." },
      { id: "c", text: "Community tenancy", rationale: "Wrong category." },
      { id: "d", text: "A Type 1 beep code", rationale: "No." },
    ],
    correct: "a",
    explanation: "Vertical scaling resizes one instance.",
    remediationLessonId: "C1-D4-O2-L3",
  }),
  q({
    id: "C1-D4-O2-ELASTIC-Q005",
    objectiveId: "C1-D4-O2",
    conceptIds: ["C1-D4-O2-ELASTIC"],
    stem: "Availability in cloud language is MOST nearly:",
    choices: [
      { id: "a", text: "The service is reachable; often expressed with zones and an SLA", rationale: "Correct." },
      { id: "b", text: "Your data can never be deleted", rationale: "Availability ≠ indestructible data." },
      { id: "c", text: "Metering is disabled", rationale: "No." },
      { id: "d", text: "Only Type 2 can be available", rationale: "No." },
    ],
    correct: "a",
    explanation: "SLAs and redundant zones are the A+ availability picture. Backups are a separate conversation.",
    remediationLessonId: "C1-D4-O2-L3",
  }),
  q({
    id: "C1-D4-O2-ELASTIC-Q006",
    objectiveId: "C1-D4-O2",
    conceptIds: ["C1-D4-O2-ELASTIC"],
    type: "multi",
    stem: "Which TWO are metered cloud items a technician should expect on an invoice? (Choose two.)",
    choices: [
      { id: "a", text: "Compute hours", rationale: "Correct." },
      { id: "b", text: "Egress GB", rationale: "Correct." },
      { id: "c", text: "CMOS beep codes", rationale: "Not billed." },
      { id: "d", text: "Type 2 window wallpaper", rationale: "Not billed." },
      { id: "e", text: "POST LEDs", rationale: "Not billed." },
    ],
    correct: ["a", "b"],
    explanation: "Measured service includes compute, storage, and data transfer — especially egress.",
    remediationLessonId: "C1-D4-O2-L3",
    tags: ["multi"],
  }),
  q({
    id: "C1-D4-O2-ELASTIC-Q007",
    objectiveId: "C1-D4-O2",
    conceptIds: ["C1-D4-O2-ELASTIC"],
    difficulty: "exam",
    stem: "Two application instances in two availability zones survive one datacenter fire. One IaaS VM with no backup does not. What is the lesson?",
    choices: [
      { id: "a", text: "Availability design is redundancy; a single VM is a hope", rationale: "Correct." },
      { id: "b", text: "Fire is impossible in public cloud", rationale: "Zones exist because failures happen." },
      { id: "c", text: "Elasticity deletes backups", rationale: "No." },
      { id: "d", text: "Zones are only for SaaS mail", rationale: "IaaS uses zones too." },
    ],
    correct: "a",
    explanation: "A+ wants you to recognize redundant instances/zones versus a single unreplicated VM.",
    remediationLessonId: "C1-D4-O2-L3",
  }),
  q({
    id: "C1-D4-O2-MULTITENANT-Q001",
    objectiveId: "C1-D4-O2",
    conceptIds: ["C1-D4-O2-MULTITENANT"],
    difficulty: "intro",
    stem: "Multitenancy means:",
    choices: [
      { id: "a", text: "Multiple customers share physical hosts with logical isolation", rationale: "Correct." },
      { id: "b", text: "Your data is published to the internet", rationale: "Misconception." },
      { id: "c", text: "Only one VM may run in a region", rationale: "Opposite of pooling." },
      { id: "d", text: "The provider cannot meter anyone", rationale: "Unrelated." },
    ],
    correct: "a",
    explanation: "Tenants are customers isolated logically on shared metal.",
    remediationLessonId: "C1-D4-O2-L1",
  }),
  q({
    id: "C1-D4-O2-MULTITENANT-Q002",
    objectiveId: "C1-D4-O2",
    conceptIds: ["C1-D4-O2-MULTITENANT"],
    stem: "A dedicated host SKU in a public cloud is used MAINLY to:",
    choices: [
      { id: "a", text: "Keep your VMs as the only guests on that box (licensing/compliance)", rationale: "Correct. Dedicated vs shared resources." },
      { id: "b", text: "Disable all networking", rationale: "No." },
      { id: "c", text: "Convert SaaS into Type 2", rationale: "No." },
      { id: "d", text: "Turn off metering", rationale: "Dedicated hosts still bill." },
    ],
    correct: "a",
    explanation: "Shared is the default; dedicated is an isolation/licensing choice.",
    remediationLessonId: "C1-D4-O2-L1",
  }),
  q({
    id: "C1-D4-O2-MULTITENANT-Q003",
    objectiveId: "C1-D4-O2",
    conceptIds: ["C1-D4-O2-MULTITENANT"],
    type: "scenario",
    scenario: "Disk latency on a public IaaS VM spikes while your CPU is idle. The provider mentions a noisy neighbor on a crowded host.",
    stem: "Which concept explains this?",
    choices: [
      { id: "a", text: "Shared resources / multitenancy", rationale: "Correct." },
      { id: "b", text: "Your CMOS battery", rationale: "No." },
      { id: "c", text: "Host-only networking on a Type 2 laptop", rationale: "This is public IaaS." },
      { id: "d", text: "RAID 0 being a backup", rationale: "No." },
    ],
    correct: "a",
    explanation: "Pooled I/O can be affected by other tenants. Dedicated hosts and quotas are the mitigations.",
    remediationLessonId: "C1-D4-O2-L3",
  }),
  q({
    id: "C1-D4-O2-MULTITENANT-Q004",
    objectiveId: "C1-D4-O2",
    conceptIds: ["C1-D4-O2-MULTITENANT"],
    stem: "Which statement about private versus public is a common mistake?",
    choices: [
      { id: "a", text: "Private automatically means secure; public automatically means unsafe", rationale: "Correct — that is the mistake. Controls matter more than the marketing word." },
      { id: "b", text: "Public platforms are multi-customer", rationale: "True." },
      { id: "c", text: "Private can still be unpatched", rationale: "True." },
      { id: "d", text: "Hybrid needs a path between environments", rationale: "True." },
    ],
    correct: "a",
    explanation: "Security is shared-responsibility and configuration, not the word 'private.'",
    remediationLessonId: "C1-D4-O2-L1",
    tags: ["misconception"],
  }),
  q({
    id: "C1-D4-O2-MULTITENANT-Q005",
    objectiveId: "C1-D4-O2",
    conceptIds: ["C1-D4-O2-MULTITENANT"],
    stem: "SaaS mail for thousands of companies on one platform is typically:",
    choices: [
      { id: "a", text: "Multitenant", rationale: "Correct." },
      { id: "b", text: "A dedicated physical Exchange server in each user's house", rationale: "That would not be SaaS pooling." },
      { id: "c", text: "Type 2 only", rationale: "Wrong axis." },
      { id: "d", text: "Non-metered by definition", rationale: "SaaS is still licensed/metered." },
    ],
    correct: "a",
    explanation: "Public SaaS is the textbook multitenant application.",
    remediationLessonId: "C1-D4-O2-L1",
  }),
  q({
    id: "C1-D4-O2-MULTITENANT-Q006",
    objectiveId: "C1-D4-O2",
    conceptIds: ["C1-D4-O2-MULTITENANT"],
    type: "multi",
    stem: "Which TWO remain the customer's responsibility even on a multitenant public cloud? (Choose two.)",
    choices: [
      { id: "a", text: "Identity and access (who can log in)", rationale: "Correct." },
      { id: "b", text: "Data classification and sharing settings", rationale: "Correct." },
      { id: "c", text: "Physical cage cameras in the region", rationale: "Provider." },
      { id: "d", text: "Replacing failed host DIMMs in the provider rack", rationale: "Provider." },
      { id: "e", text: "Utility power to the availability zone", rationale: "Provider." },
    ],
    correct: ["a", "b"],
    explanation: "Shared responsibility never hands identity and data handling entirely to the provider.",
    remediationLessonId: "C1-D4-O2-L3",
    tags: ["multi"],
  }),
  q({
    id: "C1-D4-O2-MULTITENANT-Q007",
    objectiveId: "C1-D4-O2",
    conceptIds: ["C1-D4-O2-MULTITENANT"],
    difficulty: "exam",
    stem: "Resource locks, security groups, and not reusing admin credentials across tenants are examples of:",
    choices: [
      { id: "a", text: "Using the isolation the platform offers in a multitenant world", rationale: "Correct." },
      { id: "b", text: "Making the cloud single-tenant by disabling Ethernet", rationale: "No." },
      { id: "c", text: "Type 1 beep-code policy", rationale: "No." },
      { id: "d", text: "RAID as a backup of tenancy", rationale: "No." },
    ],
    correct: "a",
    explanation: "You still have to apply the knobs. Multitenancy is not automatic safety.",
    remediationLessonId: "C1-D4-O2-L3",
  }),
];
