export type Acronym = {
  id: string;
  acronym: string;
  expansion: string;
  blurb: string;
  objectiveIds: string[];
};

export const ACRONYMS: Acronym[] = [
  { id: "AAA", acronym: "AAA", expansion: "Authentication, Authorization, and Accounting", blurb: "A framework for proving identity, granting rights, and logging activity on a network.", objectiveIds: ["C1-D2-O3", "C2-D2-O1"] },
  { id: "ACL", acronym: "ACL", expansion: "Access Control List", blurb: "Rules that permit or deny traffic or file access.", objectiveIds: ["C2-D2-O1"] },
  { id: "ADF", acronym: "ADF", expansion: "Automatic Document Feeder", blurb: "Printer/scanner tray that pulls sheets for multi-page jobs.", objectiveIds: ["C1-D3-O7"] },
  { id: "AES", acronym: "AES", expansion: "Advanced Encryption Standard", blurb: "Modern symmetric cipher used by WPA2/WPA3 and many disk tools.", objectiveIds: ["C2-D2-O3"] },
  { id: "AMD", acronym: "AMD", expansion: "Advanced Micro Devices, Inc.", blurb: "CPU vendor with its own socket families.", objectiveIds: ["C1-D3-O5"] },
  { id: "AP", acronym: "AP", expansion: "Access Point", blurb: "Wireless device that stations associate with.", objectiveIds: ["C1-D2-O5"] },
  { id: "APFS", acronym: "APFS", expansion: "Apple File System", blurb: "Default modern macOS filesystem.", objectiveIds: ["C2-D1-O1"] },
  { id: "APIPA", acronym: "APIPA", expansion: "Automatic Private IP Addressing", blurb: "Windows assigns 169.254.0.0/16 when DHCP fails. Link-local, not internet.", objectiveIds: ["C1-D2-O6"] },
  { id: "ARM", acronym: "ARM", expansion: "Advanced RISC Machine", blurb: "CPU architecture common in phones, some laptops, and Apple silicon.", objectiveIds: ["C1-D3-O5"] },
  { id: "ATX", acronym: "ATX", expansion: "Advanced Technology Extended", blurb: "Common full-size desktop motherboard form factor.", objectiveIds: ["C1-D3-O5"] },
  { id: "AUP", acronym: "AUP", expansion: "Acceptable Use Policy", blurb: "Rules for how company systems and internet may be used.", objectiveIds: ["C2-D4-O6"] },
  { id: "BEC", acronym: "BEC", expansion: "Business Email Compromise", blurb: "Fraud that impersonates executives or vendors to steal money or data.", objectiveIds: ["C2-D2-O5"] },
  { id: "BIOS", acronym: "BIOS", expansion: "Basic Input/Output System", blurb: "Legacy firmware. Modern PCs use UEFI but techs still say BIOS for firmware setup.", objectiveIds: ["C1-D3-O5"] },
  { id: "BNC", acronym: "BNC", expansion: "Bayonet Neill–Concelman", blurb: "Coax connector with a twist-lock collar. Rare on modern PCs, still on some video/RF gear.", objectiveIds: ["C1-D3-O2"] },
  { id: "BSOD", acronym: "BSOD", expansion: "Blue Screen of Death", blurb: "Windows stop error. Treat the stop code as a clue, not a personality trait of the PC.", objectiveIds: ["C2-D3-O1"] },
  { id: "BYOD", acronym: "BYOD", expansion: "Bring Your Own Device", blurb: "Personal phones/laptops used for work. Higher risk; MDM often required.", objectiveIds: ["C1-D1-O3", "C2-D2-O8"] },
  { id: "CIFS", acronym: "CIFS", expansion: "Common Internet File System", blurb: "Older name associated with SMB file sharing.", objectiveIds: ["C1-D2-O1"] },
  { id: "CMDB", acronym: "CMDB", expansion: "Configuration Management Database", blurb: "System of record for assets, relationships, and configuration items.", objectiveIds: ["C2-D4-O1"] },
  { id: "CMOS", acronym: "CMOS", expansion: "Complementary Metal-Oxide Semiconductor", blurb: "Historically the battery-backed firmware settings memory. Wrong date/time often means a dead motherboard battery.", objectiveIds: ["C1-D5-O1"] },
  { id: "CNAME", acronym: "CNAME", expansion: "Canonical Name", blurb: "DNS record that aliases one name to another.", objectiveIds: ["C1-D2-O4"] },
  { id: "CPU", acronym: "CPU", expansion: "Central Processing Unit", blurb: "Executes instructions. Must match socket, generation, and firmware.", objectiveIds: ["C1-D3-O5"] },
  { id: "DB9", acronym: "DB9", expansion: "D-sub 9-pin serial connector", blurb: "Legacy serial port still used for some consoles and industrial gear.", objectiveIds: ["C1-D3-O2"] },
  { id: "DDoS", acronym: "DDoS", expansion: "Distributed Denial of Service", blurb: "Many systems flood a target so legitimate users cannot get through.", objectiveIds: ["C2-D2-O5"] },
  { id: "DDR", acronym: "DDR", expansion: "Double Data Rate", blurb: "SDRAM family. Modules of different generations are not interchangeable.", objectiveIds: ["C1-D3-O3"] },
  { id: "DHCP", acronym: "DHCP", expansion: "Dynamic Host Configuration Protocol", blurb: "Hands out IP, mask, gateway, and DNS automatically.", objectiveIds: ["C1-D2-O1"] },
  { id: "DIMM", acronym: "DIMM", expansion: "Dual In-line Memory Module", blurb: "Desktop RAM stick form factor.", objectiveIds: ["C1-D3-O3"] },
  { id: "DKIM", acronym: "DKIM", expansion: "DomainKeys Identified Mail", blurb: "Cryptographic signature that helps prove a message really came from the domain.", objectiveIds: ["C1-D2-O4"] },
  { id: "DLP", acronym: "DLP", expansion: "Data Loss Prevention", blurb: "Controls that stop sensitive data from leaving approved channels.", objectiveIds: ["C2-D2-O1"] },
  { id: "DMARC", acronym: "DMARC", expansion: "Domain-based Message Authentication, Reporting, and Conformance", blurb: "Policy that tells receivers how to handle mail that fails SPF/DKIM.", objectiveIds: ["C1-D2-O4"] },
  { id: "DNS", acronym: "DNS", expansion: "Domain Name System", blurb: "Maps names to records. If IP works and names fail, think DNS first.", objectiveIds: ["C1-D2-O1", "C1-D2-O3"] },
  { id: "DoS", acronym: "DoS", expansion: "Denial of Service", blurb: "An attack that makes a service unavailable.", objectiveIds: ["C2-D2-O5"] },
  { id: "DRM", acronym: "DRM", expansion: "Digital Rights Management", blurb: "Technical controls that restrict copying or use of licensed content.", objectiveIds: ["C2-D4-O6"] },
  { id: "DSL", acronym: "DSL", expansion: "Digital Subscriber Line", blurb: "Internet over telephone copper. Distance from the CO matters.", objectiveIds: ["C1-D2-O7"] },
  { id: "DVI", acronym: "DVI", expansion: "Digital Visual Interface", blurb: "Video connector that may be digital, analog, or both depending on the variant.", objectiveIds: ["C1-D3-O2"] },
  { id: "ECC", acronym: "ECC", expansion: "Error-correcting code", blurb: "RAM that can detect and correct some memory errors. Common on servers.", objectiveIds: ["C1-D3-O3"] },
  { id: "EDR", acronym: "EDR", expansion: "Endpoint Detection and Response", blurb: "Endpoint security that records activity and helps hunt/respond, not just signature-scan.", objectiveIds: ["C2-D2-O4"] },
  { id: "EFS", acronym: "EFS", expansion: "Encrypting File System", blurb: "NTFS per-file/folder encryption tied to a user certificate.", objectiveIds: ["C2-D2-O2"] },
  { id: "EOL", acronym: "EOL", expansion: "End-of-life", blurb: "Vendor no longer supports the product. Unpatched by definition going forward.", objectiveIds: ["C2-D1-O1"] },
  { id: "eSATA", acronym: "eSATA", expansion: "External SATA", blurb: "SATA brought outside the case. Largely replaced by USB and NVMe enclosures.", objectiveIds: ["C1-D3-O2"] },
  { id: "ESD", acronym: "ESD", expansion: "Electrostatic discharge", blurb: "Static shock that can damage components silently. Strap, mat, and handling matter.", objectiveIds: ["C2-D4-O4"] },
  { id: "EULA", acronym: "EULA", expansion: "End-user license agreement", blurb: "Contract that defines how software may be used.", objectiveIds: ["C2-D4-O6"] },
  { id: "exFAT", acronym: "exFAT", expansion: "Extensible File Allocation Table", blurb: "Filesystem for large flash media that both Windows and macOS speak well.", objectiveIds: ["C2-D1-O1"] },
  { id: "FAT32", acronym: "FAT32", expansion: "32-bit File Allocation Table", blurb: "Legacy filesystem with a 4 GB file-size limit.", objectiveIds: ["C2-D1-O1"] },
  { id: "FRT", acronym: "FRT", expansion: "Facial Recognition Technology", blurb: "Biometric factor used by phones and Windows Hello-style sign-in.", objectiveIds: ["C2-D2-O1"] },
  { id: "FTP", acronym: "FTP", expansion: "File Transfer Protocol", blurb: "Cleartext file transfer on ports 20/21.", objectiveIds: ["C1-D2-O1"] },
  { id: "GFS", acronym: "GFS", expansion: "Grandfather-Father-Son", blurb: "Backup rotation using daily, weekly, and monthly media sets.", objectiveIds: ["C2-D4-O3"] },
  { id: "GPS", acronym: "GPS", expansion: "Global Positioning System", blurb: "Satellite location service used by mobile devices.", objectiveIds: ["C1-D1-O3"] },
  { id: "GPT", acronym: "GPT", expansion: "GUID Partition Table", blurb: "Modern partition scheme required for large disks and UEFI installs.", objectiveIds: ["C2-D1-O2"] },
  { id: "GPU", acronym: "GPU", expansion: "Graphics Processing Unit", blurb: "Renders video. May be integrated or a discrete card with its own VRAM and power plugs.", objectiveIds: ["C1-D3-O5"] },
  { id: "GUID", acronym: "GUID", expansion: "Globally Unique Identifier", blurb: "128-bit identifier used in GPT, AD objects, and many apps.", objectiveIds: ["C2-D1-O2"] },
  { id: "HDD", acronym: "HDD", expansion: "Hard Disk Drive", blurb: "Spinning magnetic storage. Clicking is a replace-and-restore event, not a tweak.", objectiveIds: ["C1-D3-O4"] },
  { id: "HDMI", acronym: "HDMI", expansion: "High-Definition Multimedia Interface", blurb: "Digital audio/video cable common on displays and TVs.", objectiveIds: ["C1-D3-O2"] },
  { id: "HSM", acronym: "HSM", expansion: "Hardware Security Module", blurb: "Dedicated crypto device for keys. Related to, but not the same as, TPM.", objectiveIds: ["C1-D3-O5"] },
  { id: "HTTP", acronym: "HTTP", expansion: "Hypertext Transfer Protocol", blurb: "Web protocol on TCP 80.", objectiveIds: ["C1-D2-O1"] },
  { id: "HTTPS", acronym: "HTTPS", expansion: "HTTP Secure", blurb: "HTTP over TLS on TCP 443.", objectiveIds: ["C1-D2-O1"] },
  { id: "IaaS", acronym: "IaaS", expansion: "Infrastructure as a Service", blurb: "Cloud provider rents VMs, storage, and networks. You still patch the OS.", objectiveIds: ["C1-D4-O2"] },
  { id: "IAM", acronym: "IAM", expansion: "Identity and Access Management", blurb: "Who a user is and what they may do across systems.", objectiveIds: ["C2-D2-O1"] },
  { id: "IMAP", acronym: "IMAP", expansion: "Internet Mail Access Protocol", blurb: "Keeps mail on the server for multi-device access. Port 143.", objectiveIds: ["C1-D2-O1"] },
  { id: "IOPS", acronym: "IOPS", expansion: "Input/Output Operations Per Second", blurb: "Storage performance measure. Collapsing IOPS is a drive/RAID clue.", objectiveIds: ["C1-D5-O2"] },
  { id: "IoT", acronym: "IoT", expansion: "Internet of Things", blurb: "Embedded devices on the network — cameras, sensors, printers with apps.", objectiveIds: ["C1-D2-O3"] },
  { id: "IP", acronym: "IP", expansion: "Internet Protocol", blurb: "Addressing and routing layer. IPv4 and IPv6 are both in A+ scope.", objectiveIds: ["C1-D2-O6"] },
  { id: "IPS", acronym: "IPS", expansion: "In-plane Switching", blurb: "LCD panel type with strong color and viewing angles.", objectiveIds: ["C1-D3-O1"] },
  { id: "ISO", acronym: "ISO", expansion: "International Organization for Standardization / disk image", blurb: "In A+ you will meet ISO files as bootable install images more often than the standards body.", objectiveIds: ["C2-D1-O10"] },
  { id: "ITX", acronym: "ITX", expansion: "Information Technology eXtended", blurb: "Small motherboard family (Mini-ITX is the common A+ size).", objectiveIds: ["C1-D3-O5"] },
  { id: "KVM", acronym: "KVM", expansion: "Keyboard-Video-Mouse", blurb: "Switch that shares input/display across multiple computers.", objectiveIds: ["C1-D3-O2"] },
  { id: "LAN", acronym: "LAN", expansion: "Local Area Network", blurb: "Network in one building or campus.", objectiveIds: ["C1-D2-O7"] },
  { id: "LC", acronym: "LC", expansion: "Lucent Connector", blurb: "Small square fiber connector, very common in datacenters.", objectiveIds: ["C1-D3-O2"] },
  { id: "LCD", acronym: "LCD", expansion: "Liquid Crystal Display", blurb: "Backlit panel family that includes IPS, TN, and VA.", objectiveIds: ["C1-D3-O1"] },
  { id: "LDAP", acronym: "LDAP", expansion: "Lightweight Directory Access Protocol", blurb: "Directory access protocol on port 389. AD uses it.", objectiveIds: ["C1-D2-O1"] },
  { id: "LED", acronym: "LED", expansion: "Light-emitting Diode", blurb: "Used in backlights, status lights, and Mini-LED displays.", objectiveIds: ["C1-D3-O1"] },
  { id: "LTE", acronym: "LTE", expansion: "Long-Term Evolution", blurb: "4G cellular technology.", objectiveIds: ["C1-D1-O3"] },
  { id: "MAC", acronym: "MAC", expansion: "Media Access Control", blurb: "48-bit hardware address on a NIC. Not the same as macOS.", objectiveIds: ["C1-D2-O5"] },
  { id: "MAN", acronym: "MAN", expansion: "Metropolitan Area Network", blurb: "Network spanning a city.", objectiveIds: ["C1-D2-O7"] },
  { id: "MBR", acronym: "MBR", expansion: "Master Boot Record", blurb: "Legacy partition table with a 2 TB practical limit.", objectiveIds: ["C2-D1-O2"] },
  { id: "MDM", acronym: "MDM", expansion: "Mobile Device Management", blurb: "Policies, apps, wipe, and inventory for phones and tablets.", objectiveIds: ["C1-D1-O3", "C2-D2-O8"] },
  { id: "MDR", acronym: "MDR", expansion: "Managed Detection and Response", blurb: "A vendor watches your telemetry and helps respond.", objectiveIds: ["C2-D2-O4"] },
  { id: "MFA", acronym: "MFA", expansion: "Multifactor Authentication", blurb: "More than one factor: something you know, have, or are.", objectiveIds: ["C2-D2-O1"] },
  { id: "MFP", acronym: "MFP", expansion: "Multifunction Printer", blurb: "Print, scan, copy, sometimes fax, in one device.", objectiveIds: ["C1-D3-O7"] },
  { id: "MMC", acronym: "MMC", expansion: "Microsoft Management Console", blurb: "Host for snap-ins such as Event Viewer and Disk Management.", objectiveIds: ["C2-D1-O4"] },
  { id: "MNDA", acronym: "MNDA", expansion: "Mutual Non-disclosure Agreement", blurb: "Two-way confidentiality contract.", objectiveIds: ["C2-D4-O6"] },
  { id: "mSATA", acronym: "mSATA", expansion: "Mini-SATA", blurb: "Older small SSD form factor, largely replaced by M.2.", objectiveIds: ["C1-D3-O4"] },
  { id: "MSDS", acronym: "MSDS", expansion: "Material Safety Data Sheet", blurb: "Now often SDS. Tells you how to handle and dispose of chemicals such as toner.", objectiveIds: ["C2-D4-O5"] },
  { id: "MX", acronym: "MX", expansion: "Mail Exchange", blurb: "DNS record that names a domain's mail servers.", objectiveIds: ["C1-D2-O4"] },
  { id: "NAC", acronym: "NAC", expansion: "Network Access Control", blurb: "Admits devices only after they meet policy (posture, identity).", objectiveIds: ["C2-D2-O1"] },
  { id: "NDA", acronym: "NDA", expansion: "Non-disclosure Agreement", blurb: "Legal duty not to share confidential information.", objectiveIds: ["C2-D4-O6"] },
  { id: "NetBIOS", acronym: "NetBIOS", expansion: "Network Basic Input/Output System", blurb: "Legacy Windows naming/session API, often over ports 137–139.", objectiveIds: ["C1-D2-O1"] },
  { id: "NFC", acronym: "NFC", expansion: "Near-field Communication", blurb: "Very short-range radio for tap-to-pay, pairing, and badges.", objectiveIds: ["C1-D1-O2"] },
  { id: "NIC", acronym: "NIC", expansion: "Network Interface Card", blurb: "The adapter that puts a device on Ethernet or Wi-Fi.", objectiveIds: ["C1-D2-O5"] },
  { id: "NTFS", acronym: "NTFS", expansion: "New Technology File System", blurb: "Windows filesystem with permissions, encryption, and large volumes.", objectiveIds: ["C2-D1-O1"] },
  { id: "NTP", acronym: "NTP", expansion: "Network Time Protocol", blurb: "Keeps clocks honest. Kerberos and logs depend on it.", objectiveIds: ["C1-D2-O3"] },
  { id: "NVMe", acronym: "NVMe", expansion: "Non-volatile Memory Express", blurb: "High-speed SSD protocol over PCIe, often in M.2 form.", objectiveIds: ["C1-D3-O4"] },
  { id: "OLED", acronym: "OLED", expansion: "Organic Light-emitting Diode", blurb: "Self-emissive display. Perfect blacks, burn-in risk on static UI.", objectiveIds: ["C1-D3-O1"] },
  { id: "ONT", acronym: "ONT", expansion: "Optical Network Terminal", blurb: "Fiber ISP device that converts light to Ethernet for the customer.", objectiveIds: ["C1-D2-O5"] },
  { id: "OS", acronym: "OS", expansion: "Operating System", blurb: "Software that manages hardware and applications.", objectiveIds: ["C2-D1-O1"] },
  { id: "OTP", acronym: "OTP", expansion: "One-time Password", blurb: "Code valid once (or briefly). TOTP is the time-based variant.", objectiveIds: ["C2-D2-O1"] },
  { id: "PaaS", acronym: "PaaS", expansion: "Platform as a Service", blurb: "Provider manages OS/runtime; you deploy the app.", objectiveIds: ["C1-D4-O2"] },
  { id: "PAM", acronym: "PAM", expansion: "Privileged Access Management", blurb: "Controls standing admin rights, often with just-in-time elevation.", objectiveIds: ["C2-D2-O1"] },
  { id: "PAN", acronym: "PAN", expansion: "Personal Area Network", blurb: "Body/desk range — Bluetooth headset to phone is a PAN.", objectiveIds: ["C1-D2-O7"] },
  { id: "PCI", acronym: "PCI", expansion: "Peripheral Component Interconnect", blurb: "Legacy expansion bus. Do not confuse with PCIe.", objectiveIds: ["C1-D3-O5"] },
  { id: "PCIe", acronym: "PCIe", expansion: "PCI Express", blurb: "High-speed serial expansion used by GPUs, NVMe, and NICs.", objectiveIds: ["C1-D3-O5"] },
  { id: "PCL", acronym: "PCL", expansion: "Printer Command Language", blurb: "Common printer page-description language, contrasted with PostScript.", objectiveIds: ["C1-D3-O7"] },
  { id: "PII", acronym: "PII", expansion: "Personally Identifiable Information", blurb: "Data that identifies a person. Handle under policy, not convenience.", objectiveIds: ["C2-D4-O6"] },
  { id: "PIN", acronym: "PIN", expansion: "Personal Identification Number", blurb: "Knowledge factor, often device-local (Windows Hello PIN is not the Microsoft password).", objectiveIds: ["C2-D2-O8"] },
  { id: "PIV", acronym: "PIV", expansion: "Personal Identity Verification", blurb: "US government smart-card standard for identity.", objectiveIds: ["C2-D2-O1"] },
  { id: "PoE", acronym: "PoE", expansion: "Power over Ethernet", blurb: "Power plus data on the same Ethernet cable. Injector or PoE switch required.", objectiveIds: ["C1-D2-O5"] },
  { id: "POP", acronym: "POP3", expansion: "Post Office Protocol v3", blurb: "Downloads mail to one client. Port 110.", objectiveIds: ["C1-D2-O1"] },
  { id: "POST", acronym: "POST", expansion: "Power-on Self-test", blurb: "Firmware checks hardware before boot. Beep patterns are clues.", objectiveIds: ["C1-D5-O1"] },
  { id: "PSU", acronym: "PSU", expansion: "Power Supply Unit", blurb: "Converts AC to DC rails. Wattage, connectors, and region voltage all matter.", objectiveIds: ["C1-D3-O6"] },
  { id: "PUP", acronym: "PUP", expansion: "Potentially Unwanted Program", blurb: "Software the user may have accepted but that behaves like adware/crapware.", objectiveIds: ["C2-D2-O4"] },
  { id: "PXE", acronym: "PXE", expansion: "Preboot Execution Environment", blurb: "Boot from the network to install or image an OS.", objectiveIds: ["C2-D1-O2"] },
  { id: "QoS", acronym: "QoS", expansion: "Quality of Service", blurb: "Prioritizes traffic such as VoIP over bulk transfers.", objectiveIds: ["C1-D5-O5"] },
  { id: "RADIUS", acronym: "RADIUS", expansion: "Remote Authentication Dial-in User Service", blurb: "Central authentication, common for enterprise Wi-Fi.", objectiveIds: ["C2-D2-O3"] },
  { id: "RAID", acronym: "RAID", expansion: "Redundant Array of Independent Disks", blurb: "Combines disks for performance and/or redundancy. Not a backup.", objectiveIds: ["C1-D3-O4"] },
  { id: "RAM", acronym: "RAM", expansion: "Random-access Memory", blurb: "Volatile working memory. Contents vanish when power is gone.", objectiveIds: ["C1-D3-O3"] },
  { id: "RDP", acronym: "RDP", expansion: "Remote Desktop Protocol", blurb: "Windows remote GUI on TCP 3389.", objectiveIds: ["C1-D2-O1", "C2-D4-O9"] },
  { id: "ReFS", acronym: "ReFS", expansion: "Resilient File System", blurb: "Microsoft filesystem aimed at resiliency, seen on some Windows SKUs/workloads.", objectiveIds: ["C2-D1-O1"] },
  { id: "RFID", acronym: "RFID", expansion: "Radio-frequency Identification", blurb: "Tags and badges read over a short radio range, longer than NFC typically.", objectiveIds: ["C1-D2-O2"] },
  { id: "RJ11", acronym: "RJ11", expansion: "Registered Jack 11", blurb: "Telephone connector, narrower than RJ45.", objectiveIds: ["C1-D3-O2"] },
  { id: "RJ45", acronym: "RJ45", expansion: "Registered Jack 45", blurb: "8P8C Ethernet connector.", objectiveIds: ["C1-D3-O2"] },
  { id: "RMM", acronym: "RMM", expansion: "Remote Monitoring and Management", blurb: "MSP-style agent for inventory, patching, and remote control.", objectiveIds: ["C2-D4-O9"] },
  { id: "RSR", acronym: "RSR", expansion: "Rapid Security Response", blurb: "Apple's out-of-band security patches between full macOS updates.", objectiveIds: ["C2-D1-O8"] },
  { id: "SaaS", acronym: "SaaS", expansion: "Software as a Service", blurb: "Provider runs the app. You use it in a browser or client. Email and docs suites are typical.", objectiveIds: ["C1-D4-O2"] },
  { id: "SAML", acronym: "SAML", expansion: "Security Assertion Markup Language", blurb: "Federation protocol used for SSO between identity providers and apps.", objectiveIds: ["C2-D2-O1"] },
  { id: "SAN", acronym: "SAN", expansion: "Storage Area Network", blurb: "Network dedicated to block storage.", objectiveIds: ["C1-D2-O7"] },
  { id: "SAS", acronym: "SAS", expansion: "Serial Attached SCSI", blurb: "Enterprise disk interface. Different from SATA even when the connector looks related.", objectiveIds: ["C1-D3-O4"] },
  { id: "SATA", acronym: "SATA", expansion: "Serial ATA", blurb: "Common HDD/SSD interface. Also a power connector shape.", objectiveIds: ["C1-D3-O4"] },
  { id: "SC", acronym: "SC", expansion: "Subscriber Connector", blurb: "Square fiber connector, push-pull.", objectiveIds: ["C1-D3-O2"] },
  { id: "SCADA", acronym: "SCADA", expansion: "Supervisory Control and Data Acquisition", blurb: "Industrial control systems. Treat them as legacy/embedded on A+.", objectiveIds: ["C1-D2-O3"] },
  { id: "SFTP", acronym: "SFTP", expansion: "SSH File Transfer Protocol", blurb: "File transfer inside SSH (port 22), not FTP.", objectiveIds: ["C1-D2-O1"] },
  { id: "SIM", acronym: "SIM", expansion: "Subscriber Identity Module", blurb: "Identifies a cellular subscriber. eSIM is the soldered/programmable variant.", objectiveIds: ["C1-D1-O3"] },
  { id: "SLA", acronym: "SLA", expansion: "Service-level Agreement", blurb: "Promised response/resolve times. Internal or third-party.", objectiveIds: ["C2-D4-O1"] },
  { id: "SMART", acronym: "S.M.A.R.T.", expansion: "Self-Monitoring, Analysis, and Reporting Technology", blurb: "Drive health telemetry. A SMART failure is a replace-the-drive event.", objectiveIds: ["C1-D5-O2"] },
  { id: "SMB", acronym: "SMB", expansion: "Server Message Block", blurb: "Windows file/printer sharing protocol on TCP 445.", objectiveIds: ["C1-D2-O1"] },
  { id: "SMS", acronym: "SMS", expansion: "Short Message Service", blurb: "Text messages. Also an MFA channel, weaker than an authenticator app.", objectiveIds: ["C2-D2-O1"] },
  { id: "SMTP", acronym: "SMTP", expansion: "Simple Mail Transfer Protocol", blurb: "Sends email. Port 25.", objectiveIds: ["C1-D2-O1"] },
  { id: "SODIMM", acronym: "SODIMM", expansion: "Small Outline DIMM", blurb: "Laptop RAM form factor.", objectiveIds: ["C1-D1-O1", "C1-D3-O3"] },
  { id: "SOHO", acronym: "SOHO", expansion: "Small Office/Home Office", blurb: "The small-network environment A+ tests constantly.", objectiveIds: ["C1-D2-O6"] },
  { id: "SOP", acronym: "SOP", expansion: "Standard Operating Procedure", blurb: "Written repeatable process — imaging, onboarding, malware response.", objectiveIds: ["C2-D4-O1"] },
  { id: "SPF", acronym: "SPF", expansion: "Sender Policy Framework", blurb: "DNS TXT policy listing servers allowed to send mail for a domain.", objectiveIds: ["C1-D2-O4"] },
  { id: "SPICE", acronym: "SPICE", expansion: "Simple Protocol for Independent Computing Environments", blurb: "Open remote-display protocol used by some virtualization stacks.", objectiveIds: ["C2-D4-O9"] },
  { id: "SQL", acronym: "SQL", expansion: "Structured Query Language", blurb: "Database language. SQL injection is in A+ as a concept, not a coding exam.", objectiveIds: ["C2-D2-O5"] },
  { id: "SSD", acronym: "SSD", expansion: "Solid-state Drive", blurb: "Flash storage. No seeking. Different failure modes than HDDs.", objectiveIds: ["C1-D3-O4"] },
  { id: "SSH", acronym: "SSH", expansion: "Secure Shell", blurb: "Encrypted remote shell on TCP 22.", objectiveIds: ["C1-D2-O1"] },
  { id: "SSID", acronym: "SSID", expansion: "Service Set Identifier", blurb: "The Wi-Fi network name. Hiding it is not a security control.", objectiveIds: ["C2-D2-O10"] },
  { id: "SSO", acronym: "SSO", expansion: "Single Sign-on", blurb: "One authentication event unlocks many apps.", objectiveIds: ["C2-D2-O1"] },
  { id: "ST", acronym: "ST", expansion: "Straight Tip", blurb: "Round bayonet fiber connector.", objectiveIds: ["C1-D3-O2"] },
  { id: "TACACS", acronym: "TACACS+", expansion: "Terminal Access Controller Access-Control System", blurb: "Cisco-associated AAA protocol, often for device administration.", objectiveIds: ["C2-D2-O3"] },
  { id: "TCP", acronym: "TCP", expansion: "Transmission Control Protocol", blurb: "Reliable, ordered, connection-oriented transport.", objectiveIds: ["C1-D2-O1"] },
  { id: "TKIP", acronym: "TKIP", expansion: "Temporal Key Integrity Protocol", blurb: "Legacy WPA encryption. Prefer AES. Know it so you can recognize a weak AP.", objectiveIds: ["C2-D2-O3"] },
  { id: "TN", acronym: "TN", expansion: "Twisted Nematic", blurb: "Fast, cheap LCD with poor viewing angles and color.", objectiveIds: ["C1-D3-O1"] },
  { id: "TOTP", acronym: "TOTP", expansion: "Time-based One-time Password", blurb: "Authenticator-app codes that rotate with the clock.", objectiveIds: ["C2-D2-O1"] },
  { id: "TPM", acronym: "TPM", expansion: "Trusted Platform Module", blurb: "On-board crypto chip. BitLocker and Windows 11 hardware requirements use it.", objectiveIds: ["C1-D3-O5", "C2-D1-O3"] },
  { id: "UAC", acronym: "UAC", expansion: "User Account Control", blurb: "Windows prompt that separates standard and admin tokens.", objectiveIds: ["C2-D2-O2"] },
  { id: "UDP", acronym: "UDP", expansion: "User Datagram Protocol", blurb: "Connectionless transport. Fast, no built-in reliability. DHCP and many real-time apps use it.", objectiveIds: ["C1-D2-O1"] },
  { id: "UEFI", acronym: "UEFI", expansion: "Unified Extensible Firmware Interface", blurb: "Modern firmware replacing BIOS. Secure Boot lives here.", objectiveIds: ["C1-D3-O5"] },
  { id: "UPnP", acronym: "UPnP", expansion: "Universal Plug and Play", blurb: "Lets LAN devices open router ports automatically. Convenient and risky.", objectiveIds: ["C2-D2-O10"] },
  { id: "UPS", acronym: "UPS", expansion: "Uninterruptible Power Supply", blurb: "Battery backup for brownouts and blackouts. Not the same as a surge strip.", objectiveIds: ["C2-D4-O5"] },
  { id: "USB", acronym: "USB", expansion: "Universal Serial Bus", blurb: "Family of connectors and speeds. USB-C is a connector shape, not automatically a speed.", objectiveIds: ["C1-D1-O2"] },
  { id: "UTM", acronym: "UTM", expansion: "Unified Threat Management", blurb: "Appliance combining firewall, IPS, AV, and related services.", objectiveIds: ["C1-D2-O3"] },
  { id: "VA", acronym: "VA", expansion: "Vertical Alignment", blurb: "LCD type with strong contrast, moderate angles.", objectiveIds: ["C1-D3-O1"] },
  { id: "VDI", acronym: "VDI", expansion: "Virtual Desktop Infrastructure", blurb: "Desktop OS runs in the datacenter; the user sees a remote session.", objectiveIds: ["C1-D4-O1"] },
  { id: "VGA", acronym: "VGA", expansion: "Video Graphics Array", blurb: "Analog 15-pin video. No native audio. Easy to bend pins.", objectiveIds: ["C1-D3-O2"] },
  { id: "VLAN", acronym: "VLAN", expansion: "Virtual LAN", blurb: "Logical broadcast domain on a switch. Isolation without extra cables.", objectiveIds: ["C1-D2-O4"] },
  { id: "VM", acronym: "VM", expansion: "Virtual Machine", blurb: "Guest OS on a hypervisor.", objectiveIds: ["C1-D4-O1"] },
  { id: "VNC", acronym: "VNC", expansion: "Virtual Network Computing", blurb: "Cross-platform remote framebuffer. Encrypt it or tunnel it.", objectiveIds: ["C2-D4-O9"] },
  { id: "VoIP", acronym: "VoIP", expansion: "Voice over IP", blurb: "Phone audio on the data network. Jitter and latency ruin it.", objectiveIds: ["C1-D5-O5"] },
  { id: "VPN", acronym: "VPN", expansion: "Virtual Private Network", blurb: "Encrypted tunnel across an untrusted network.", objectiveIds: ["C1-D2-O4"] },
  { id: "VRAM", acronym: "VRAM", expansion: "Video RAM", blurb: "Memory on a GPU. Apps can require a minimum.", objectiveIds: ["C2-D1-O10"] },
  { id: "WAN", acronym: "WAN", expansion: "Wide Area Network", blurb: "Network over long distance — typically the ISP link.", objectiveIds: ["C1-D2-O7"] },
  { id: "WAP", acronym: "WAP", expansion: "Wireless Access Point", blurb: "Another name for AP.", objectiveIds: ["C1-D2-O5"] },
  { id: "WinRM", acronym: "WinRM", expansion: "Windows Remote Management", blurb: "Windows remote management protocol used by PowerShell remoting.", objectiveIds: ["C2-D4-O9"] },
  { id: "WISP", acronym: "WISP", expansion: "Wireless Internet Service Provider", blurb: "Fixed wireless ISP. Useful when cable/fiber/cellular are missing.", objectiveIds: ["C1-D2-O7"] },
  { id: "WLAN", acronym: "WLAN", expansion: "Wireless LAN", blurb: "Wi-Fi network.", objectiveIds: ["C1-D2-O7"] },
  { id: "WPA", acronym: "WPA", expansion: "Wi-Fi Protected Access", blurb: "Wi-Fi security family. A+ current scope emphasizes WPA2 and WPA3.", objectiveIds: ["C2-D2-O3"] },
  { id: "WWAN", acronym: "WWAN", expansion: "Wireless Wide Area Network", blurb: "Cellular data network from a PC's point of view.", objectiveIds: ["C2-D1-O7"] },
  { id: "XDR", acronym: "XDR", expansion: "Extended Detection and Response", blurb: "Detection/response across email, identity, cloud, and endpoints — broader than EDR.", objectiveIds: ["C2-D2-O4"] },
  { id: "XFS", acronym: "XFS", expansion: "XFS filesystem", blurb: "High-performance Linux filesystem listed in current A+ objectives.", objectiveIds: ["C2-D1-O1"] },
  { id: "XSS", acronym: "XSS", expansion: "Cross-site Scripting", blurb: "Injecting script into a web app so another user's browser runs it.", objectiveIds: ["C2-D2-O5"] },
];

export function findAcronym(term: string): Acronym | undefined {
  const t = term.replace(/\./g, "").toUpperCase();
  return ACRONYMS.find(
    (a) => a.acronym.replace(/\./g, "").toUpperCase() === t || a.id === t,
  );
}
