import type { Lab } from "../schema";

export const LABS: Lab[] = [
  {
    id: "FND-D0-O5-LANDSCAPE-LAB",
    slug: "it-landscape",
    title: "IT landscape explorer",
    kind: "hardware",
    objectiveIds: ["FND-D0-O5", "FND-D0-O2"],
    conceptIds: ["FND-D0-O5-UNITS", "FND-D0-O2-CYCLE"],
    component: "LandscapeLab",
    description:
      "Click a desktop PC, laptop, network closet, printer, phone, and cloud service to build mental models before Core 1.",
    solution:
      "Each hotspot is a system you will later disassemble, configure, or troubleshoot. The PC is local compute, the closet is forwarding and addressing, the printer is an endpoint with its own OS, the phone is a mobile computer, and the cloud is someone else's computer on a metered network.",
    estimatedMinutes: 12,
  },
  {
    id: "C1-D1-O1-LAPTOP-LAB",
    slug: "laptop-upgrade",
    title: "Laptop FRU upgrade lab",
    kind: "hardware",
    objectiveIds: ["C1-D1-O1"],
    conceptIds: ["C1-D1-O1-SODIMM", "C1-D1-O1-BATTERY", "C1-D1-O1-WLAN"],
    component: "LaptopUpgradeLab",
    description:
      "Match SODIMM, OEM battery pack, and M.2 Wi-Fi card to the correct laptop bays; leave desktop-only parts unused.",
    solution:
      "Memory bay takes SODIMM DDR4, not desktop DIMM. Swollen packs need an OEM Li-ion replacement, not a CMOS coin. WLAN uses an M.2 card with antenna leads — not a desktop PCIe NIC.",
    estimatedMinutes: 12,
    capstone: true,
  },
  {
    id: "C1-D3-O3-RAM-LAB",
    slug: "ram-install",
    title: "RAM install matching lab",
    kind: "hardware",
    objectiveIds: ["C1-D3-O3"],
    conceptIds: [
      "C1-D3-O3-DIMM",
      "C1-D3-O3-SODIMM",
      "C1-D3-O3-DDR",
      "C1-D3-O3-ECC",
      "C1-D3-O3-CHANNELS",
    ],
    component: "RamInstallLab",
    description:
      "Match DIMM vs SODIMM, DDR generation, dual-channel kit, and ECC to desktop, laptop, and server tickets.",
    solution:
      "Desktop dual-channel takes a matched DDR4 DIMM kit. Laptops take SODIMM. Hypervisor hosts need ECC on a supported platform. Wrong-generation DDR5, SODIMM adapters, and non-ECC RGB fail those tickets.",
    estimatedMinutes: 12,
    capstone: true,
  },
  {
    id: "C1-D4-O2-CLOUD-LAB",
    slug: "cloud-service-models",
    title: "Cloud service model matching lab",
    kind: "network",
    objectiveIds: ["C1-D4-O2"],
    conceptIds: ["C1-D4-O2-IAAS", "C1-D4-O2-PAAS", "C1-D4-O2-SAAS"],
    component: "CloudServiceLab",
    description:
      "Match IaaS, PaaS, and SaaS tickets; leave on-prem Type 1, thin-provision, and container distractors unused.",
    solution:
      "IaaS is a Windows VM you patch and RDP into. PaaS is git-push without managing the OS/runtime. SaaS is licensed email/docs in a browser. Bare-metal ESXi, datastore fills, and laptop Docker are not service models.",
    estimatedMinutes: 12,
    capstone: true,
  },
  {
    id: "C1-D3-O4-RAID-LAB",
    slug: "raid-builder",
    title: "RAID builder and failure lab",
    kind: "storage",
    objectiveIds: ["C1-D3-O4", "C1-D5-O2"],
    conceptIds: [
      "C1-D3-O4-RAID0",
      "C1-D3-O4-RAID1",
      "C1-D3-O4-RAID5",
      "C1-D3-O4-RAID6",
      "C1-D3-O4-RAID10",
    ],
    component: "RaidLab",
    description:
      "Stripe, mirror, and parity arrays. Fail disks and watch availability and capacity change.",
    solution:
      "RAID 0 has no redundancy. RAID 1 mirrors. RAID 5 survives one disk. RAID 6 survives two. RAID 10 is striped mirrors. RAID is not a backup.",
    estimatedMinutes: 20,
    capstone: true,
  },
  {
    id: "C1-D3-O5-MOBO-LAB",
    slug: "motherboard-explorer",
    title: "Motherboard explorer",
    kind: "hardware",
    objectiveIds: ["C1-D3-O5"],
    conceptIds: ["C1-D3-O5-ATX", "C1-D3-O5-PCIE", "C1-D3-O5-UEFI"],
    component: "MotherboardLab",
    description:
      "Learn, label, identify, build, and troubleshoot a desktop motherboard.",
    solution:
      "CPU goes in the socket with correct orientation, RAM in the channel-colored slots, NVMe in M.2, GPU in the top x16, 24-pin and EPS power must both seat.",
    estimatedMinutes: 18,
    capstone: true,
  },
  {
    id: "C1-D3-O2-CABLE-LAB",
    slug: "cable-lab",
    title: "Connector museum and T568 lab",
    kind: "hardware",
    objectiveIds: ["C1-D3-O2"],
    conceptIds: ["C1-D3-O2-T568", "C1-D3-O2-RJ45", "C1-D3-O2-USB"],
    component: "CableLab",
    description: "Identify connectors and terminate T568A vs T568B.",
    solution:
      "T568B is the more common US sequence: O/O, O, G/O, Bl, Bl/O, G, Br/O, Br. Both ends the same standard produce a straight-through cable.",
    estimatedMinutes: 15,
    capstone: true,
  },
  {
    id: "C1-D2-O5-RACK-LAB",
    slug: "network-builder",
    title: "Network closet builder",
    kind: "network",
    objectiveIds: ["C1-D2-O5", "C1-D2-O6"],
    conceptIds: ["C1-D2-O5-ROUTER", "C1-D2-O5-SWITCH", "C1-D2-O5-ONT"],
    component: "NetworkBuilderLab",
    description: "Connect ISP → ONT/modem → router/firewall → switch → AP/endpoints.",
    solution:
      "The WAN handoff terminates at the modem/ONT. The router is the LAN gateway and NAT boundary. Switches fan out. APs attach to switched LAN, not the WAN port.",
    estimatedMinutes: 15,
    capstone: true,
  },
  {
    id: "C1-D2-O6-ROUTER-LAB",
    slug: "soho-router",
    title: "SOHO router simulator",
    kind: "network",
    objectiveIds: ["C1-D2-O6", "C2-D2-O10"],
    conceptIds: ["C1-D2-O6-IPV4", "C1-D2-O6-GATEWAY", "C2-D2-O10-UPNP"],
    component: "RouterLab",
    description:
      "Configure LAN IP, DHCP, Wi-Fi, DNS, guest, and firewall on a fake admin UI.",
    solution:
      "Change default credentials, set a private LAN, scope that does not include the router address, WPA3, guest isolation, and disable UPnP unless a documented exception exists.",
    estimatedMinutes: 18,
    capstone: true,
  },
  {
    id: "C1-D2-O1-PORTS-LAB",
    slug: "ports-drill",
    title: "Official 2.1 ports drill",
    kind: "network",
    objectiveIds: ["C1-D2-O1"],
    conceptIds: [
      "C1-D2-O1-PORTS",
      "C1-D2-O1-FTP",
      "C1-D2-O1-SSH",
      "C1-D2-O1-DNS",
      "C1-D2-O1-DHCP",
      "C1-D2-O1-HTTP",
      "C1-D2-O1-SMB",
      "C1-D2-O1-RDP",
    ],
    component: "PortsDrillLab",
    description:
      "Match help-desk tickets (send mail, names, APIPA, shell, share, RDP) to official 2.1 ports; leave Telnet/HTTP/FTP unused.",
    solution:
      "SMTP 25 for send, DNS 53 for names, DHCP 67/68 for APIPA, SSH 22 for encrypted shell, SMB 445 for Windows shares, RDP 3389 for remote desktop. Telnet 23, HTTP 80, and FTP 20/21 are not the answers for this queue.",
    estimatedMinutes: 14,
    capstone: true,
  },

  {
    id: "C1-D2-O2-WIFI-LAB",
    slug: "wifi-lab",
    title: "Wi-Fi interference lab",
    kind: "network",
    objectiveIds: ["C1-D2-O2", "C1-D5-O5"],
    conceptIds: ["C1-D2-O2-24GHZ", "C1-D2-O2-5GHZ", "C1-D2-O2-CHANNEL"],
    component: "WifiLab",
    description: "Move APs, pick bands and channels, and watch overlap.",
    solution:
      "2.4 GHz travels farther and collides more. 5/6 GHz are wider and cleaner at short range. Overlapping co-channel APs should be spaced in the plan, not stacked on channel 6.",
    estimatedMinutes: 12,
  },
  {
    id: "C2-D1-O5-CMD-LAB",
    slug: "windows-cli",
    title: "Windows command prompt lab",
    kind: "cli",
    objectiveIds: ["C2-D1-O5", "C2-D3-O1"],
    conceptIds: ["C2-D1-O5-IPCONFIG", "C2-D1-O5-PING", "C2-D1-O5-SFC"],
    component: "WindowsCliLab",
    description: "Sandboxed command prompt. It cannot touch the host.",
    solution:
      "ipconfig /all shows DHCP vs static. ping the gateway, then a public IP, then a name — that order separates NIC, path, and DNS.",
    estimatedMinutes: 20,
    capstone: true,
  },
  {
    id: "C2-D1-O9-LINUX-LAB",
    slug: "linux-terminal",
    title: "Linux terminal lab",
    kind: "cli",
    objectiveIds: ["C2-D1-O9"],
    conceptIds: ["C2-D1-O9-CHMOD", "C2-D1-O9-SUDO", "C2-D1-O9-ETC"],
    component: "LinuxCliLab",
    description: "Virtual Linux filesystem and command set from the objectives.",
    solution:
      "pwd/ls to locate yourself, cat the /etc files, chmod/chown to fix permissions, ip/ping for network, journal-unaware systemd status conceptually via systemctl-like help.",
    estimatedMinutes: 20,
    capstone: true,
  },
  {
    id: "C2-D1-O4-WINTOOLS-LAB",
    slug: "windows-tools",
    title: "Windows tools lab",
    kind: "os",
    objectiveIds: ["C2-D1-O4", "C2-D3-O1"],
    conceptIds: ["C2-D1-O4-TASKMGR", "C2-D1-O4-EVENTVWR", "C2-D1-O4-DISKMGMT"],
    component: "WindowsToolsLab",
    description: "Task Manager, Event Viewer, Device Manager, and Disk Management missions.",
    solution:
      "High CPU lives in Task Manager Processes. Device errors live in Device Manager. Boot and service failures leave Event Viewer breadcrumbs. Capacity and letters live in Disk Management.",
    estimatedMinutes: 18,
    capstone: true,
  },
  {
    id: "C2-D1-O8-MACOS-LAB",
    slug: "macos-support",
    title: "macOS support lab",
    kind: "os",
    objectiveIds: ["C2-D1-O8"],
    conceptIds: ["C2-D1-O8-TIMEMACHINE", "C2-D1-O8-FILEVAULT"],
    component: "MacOsLab",
    description: "Simplified macOS desktop for install, backup, and FileVault tasks.",
    solution:
      "Apps come from App Store, .dmg, or .pkg. Time Machine is the backup story. FileVault is full-disk encryption.",
    estimatedMinutes: 12,
    capstone: true,
  },
  {
    id: "C2-D1-O3-EDITION-LAB",
    slug: "windows-editions",
    title: "Windows edition matching lab",
    kind: "os",
    objectiveIds: ["C2-D1-O3"],
    conceptIds: [
      "C2-D1-O3-HOME",
      "C2-D1-O3-PRO",
      "C2-D1-O3-ENT",
      "C2-D1-O3-BITLOCKER",
      "C2-D1-O3-GPEDIT",
    ],
    component: "WindowsEditionLab",
    description:
      "Match Home, Pro, Pro for Workstations, and Enterprise to domain join, RDP host, BitLocker, gpedit, RAM, and volume-licensing tickets.",
    solution:
      "Home is consumer-only. Pro unlocks AD, RDP host, BitLocker, and gpedit. Pro for Workstations adds 6 TB / four sockets / ReFS. Enterprise is the volume AppLocker SKU. Home N and ChromeOS do not satisfy those tickets.",
    estimatedMinutes: 12,
    capstone: true,
  },
  {
    id: "C1-D3-O8-PRINTER-LAB",
    slug: "printer-lab",
    title: "Printer output and maintenance lab",
    kind: "printer",
    objectiveIds: ["C1-D3-O8", "C1-D5-O6"],
    conceptIds: ["C1-D3-O8-LASER", "C1-D5-O6-GHOST", "C1-D5-O6-FADED"],
    component: "PrinterLab",
    description: "Match sample pages to subsystems and maintenance actions.",
    solution:
      "Faded laser often means toner or density. Repeating marks follow drum circumference. Ghosting often implicates the fuser or drum. Garbled output is language/driver, not paper.",
    estimatedMinutes: 15,
    capstone: true,
  },
  {
    id: "C2-D2-O1-AUTH-LAB",
    slug: "auth-factors",
    title: "Physical and logical controls lab",
    kind: "security",
    objectiveIds: ["C2-D2-O1"],
    conceptIds: [
      "C2-D2-O1-VESTIBULE",
      "C2-D2-O1-MFA",
      "C2-D2-O1-PAM",
      "C2-D2-O1-ZEROTRUST",
    ],
    component: "AuthFactorsLab",
    description:
      "Match vestibule, bollards, password+TOTP MFA, and PAM/JIT to four security tickets; leave password+PIN and camera-only unused.",
    solution:
      "Tailgating needs an access control vestibule. Vehicle ramming needs bollards. SaaS MFA needs know+have (password + authenticator TOTP), not two knowledge secrets. Standing Domain Admin is fixed with PAM/JIT. Cameras record — they do not interlock doors.",
    estimatedMinutes: 12,
    capstone: true,
  },
  {
    id: "C2-D2-O5-PHISH-LAB",
    slug: "phishing-lab",
    title: "Phishing and social-engineering lab",
    kind: "security",
    objectiveIds: ["C2-D2-O5", "C2-D2-O4"],
    conceptIds: ["C2-D2-O5-PHISH", "C2-D2-O5-BEC", "C2-D2-O5-EVILTWIN"],
    component: "PhishingLab",
    description: "Inbox, evil-twin SSID list, and QR/vishing scenarios.",
    solution:
      "Look at the actual domain, urgency + money, mismatched reply-to, and Wi-Fi SSIDs that clone the office name without the captive-portal you expect.",
    estimatedMinutes: 15,
    capstone: true,
  },
  {
    id: "C2-D2-O6-MALWARE-LAB",
    slug: "malware-response",
    title: "Malware removal sequence lab",
    kind: "security",
    objectiveIds: ["C2-D2-O6"],
    conceptIds: ["C2-D2-O6-QUARANTINE", "C2-D2-O6-SYSRESTORE", "C2-D2-O6-REIMAGE"],
    component: "MalwareLab",
    description: "Reorder the current 10-step SOHO malware process, then run an infection simulation.",
    solution:
      "Verify, quarantine, disable System Restore on Windows Home, remediate, update tools, scan, reimage if needed, schedule, re-enable restore points, educate.",
    estimatedMinutes: 16,
    capstone: true,
  },
  {
    id: "C2-D2-O2-ACL-LAB",
    slug: "permissions-lab",
    title: "NTFS and share permissions lab",
    kind: "security",
    objectiveIds: ["C2-D2-O2"],
    conceptIds: ["C2-D2-O2-NTFS", "C2-D2-O2-SHAREPERM"],
    component: "PermissionsLab",
    description: "Effective permissions change as groups, NTFS, and share ACLs change.",
    solution:
      "Share permissions cap remote access; NTFS is the real ACL on the volume. Most restrictive combination wins for remote users. Local users ignore the share ACL.",
    estimatedMinutes: 12,
  },
  {
    id: "C2-D4-O1-TICKET-LAB",
    slug: "ticketing-lab",
    title: "Help-desk ticket lab",
    kind: "ticket",
    objectiveIds: ["C2-D4-O1"],
    conceptIds: ["C2-D4-O1-TICKET", "C2-D4-O1-SLA"],
    component: "TicketLab",
    description: "Turn 'PC broken' into a documented, prioritized incident.",
    solution:
      "Capture user, device, category, severity, reproduction, and next action. Close with resolution notes a stranger could follow.",
    estimatedMinutes: 12,
    capstone: true,
  },
  {
    id: "C2-D4-O2-CHANGE-LAB",
    slug: "change-pipeline-lab",
    title: "Change management pipeline",
    kind: "ticket",
    objectiveIds: ["C2-D4-O2"],
    conceptIds: ["C2-D4-O2-CAB", "C2-D4-O2-ROLLBACK", "C2-D4-O2-FREEZE", "C2-D4-O2-EMERGENCY"],
    component: "ChangePipelineLab",
    description:
      "Classify standard, normal, and emergency changes during a freeze and attach real rollback plans.",
    solution:
      "Standard follows the SOP; normal waits for CAB and a window; emergency is for outages/exploits with paperwork after. Rollback is a written reverse, not hope.",
    estimatedMinutes: 12,
    capstone: true,
  },
  {
    id: "C2-D4-O3-BACKUP-LAB",
    slug: "backup-lab",
    title: "Backup and restore lab",
    kind: "ticket",
    objectiveIds: ["C2-D4-O3"],
    conceptIds: ["C2-D4-O3-FULL", "C2-D4-O3-INCR", "C2-D4-O3-GFS"],
    component: "BackupLab",
    description: "Pick the restore chain for full/incremental/differential and GFS.",
    solution:
      "Incremental restore needs the last full plus every incremental after it. Differential needs the last full plus the latest differential.",
    estimatedMinutes: 12,
    capstone: true,
  },
  {
    id: "C2-D4-O7-VOICE-LAB",
    slug: "voice-helpdesk",
    title: "Voice help-desk shift",
    kind: "voice",
    objectiveIds: ["C2-D4-O7"],
    conceptIds: ["C2-D4-O7-LISTEN", "C2-D4-O7-DIFFICULT"],
    component: "VoiceLab",
    description: "Listen to customer calls (or read transcripts) and pick BEST responses.",
    solution:
      "Acknowledge, restate, set a timeline, and avoid arguing. Technical truth without empathy still fails the objective.",
    estimatedMinutes: 18,
    capstone: true,
  },
  {
    id: "C1-D5-O3-DISPLAY-LAB",
    slug: "display-fault-match",
    title: "Display and projector fault matching",
    kind: "hardware",
    objectiveIds: ["C1-D5-O3"],
    conceptIds: [
      "C1-D5-O3-SOURCE",
      "C1-D5-O3-BURNIN",
      "C1-D5-O3-DEADPIXEL",
      "C1-D5-O3-PROJECTOR",
    ],
    component: "DisplayFaultLab",
    description:
      "Match no-signal, burn-in, dead pixel, dim lamp, and thermal shutdown tickets to the correct display/projector cause; leave GPU-first and reimage distractors unused.",
    solution:
      "Source/input and Win+P before hardware. Burn-in is a stable UI ghost on OLED. Dead pixels stay put. Dim high-hour projectors are lamps/filters. Early shutdown with packed vents is thermal. GPU-first when the laptop panel works, reimage for a pixel, and RAID for soft resolution stay unmatched.",
    estimatedMinutes: 12,
    capstone: true,
  },
  {
    id: "C1-D5-SHIFT-LAB",
    slug: "ticket-shift-core1",
    title: "Core 1 troubleshooting shift",
    kind: "capstone",
    objectiveIds: ["C1-D5-O1", "C1-D5-O2", "C1-D5-O5", "C1-D5-O6"],
    conceptIds: ["C1-D5-O1-POST", "C1-D5-O5-LIMITED", "C1-D5-O6-FADED"],
    component: "TicketShiftLab",
    description: "A randomized 8-ticket hardware/network shift.",
    solution:
      "FIRST actions gather information or make the environment safe. Replacing parts before testing is a common miss.",
    estimatedMinutes: 25,
    capstone: true,
  },
  {
    id: "C2-D3-O2-MOBILE-LAB",
    slug: "mobile-os-triage",
    title: "Mobile OS symptom triage lab",
    kind: "os",
    objectiveIds: ["C2-D3-O2"],
    conceptIds: [
      "C2-D3-O2-APPCRASH",
      "C2-D3-O2-MOBILEUPDATE",
      "C2-D3-O2-AUTOROTATE",
    ],
    component: "MobileOsLab",
    description:
      "Match app crash, OS update stall, battery drain, and autorotate tickets to the BEST FIRST software actions.",
    solution:
      "One app → force-stop/clear cache. Update stall → free space, charge, Wi-Fi. Overnight drain → Battery usage on the named app. No rotate → rotation lock. Leave factory reset, blind battery swap, jailbreak, and digitizer FIRST unused.",
    estimatedMinutes: 12,
    capstone: true,
  },
  {
    id: "C2-D3-SHIFT-LAB",
    slug: "ticket-shift-core2",
    title: "Core 2 software-troubleshooting shift",
    kind: "capstone",
    objectiveIds: ["C2-D3-O1", "C2-D3-O4", "C2-D4-O10"],
    conceptIds: ["C2-D3-O1-BSOD", "C2-D3-O4-REDIRECT", "C2-D4-O10-HALLUCINATION"],
    component: "TicketShiftLab",
    description: "A randomized software, security, and AI-use shift.",
    solution:
      "Separate OS faults from malware symptoms. Treat AI-generated commands as unverified until you read them.",
    estimatedMinutes: 25,
    capstone: true,
  },
  {
    id: "C1-D3-O1-DISPLAY-LAB",
    slug: "display-match",
    title: "Display technology matching lab",
    kind: "hardware",
    objectiveIds: ["C1-D3-O1"],
    conceptIds: [
      "C1-D3-O1-IPS",
      "C1-D3-O1-TN",
      "C1-D3-O1-OLED",
      "C1-D3-O1-DIGITIZER",
    ],
    component: "DisplayMatchLab",
    description:
      "Match IPS, high-refresh TN, OLED, and digitizer FRU choices to design, esports, film, and touch-dead tickets; leave CCFL inverter and whole-panel-for-touch unused.",
    solution:
      "IPS for wide-angle design reviews. Fast TN/high-refresh for esports. OLED for dark-room contrast (burn-in risk). Digitizer when the image is fine but touch is dead. CCFL inverters are not for LED/OLED; do not order a whole panel for touch alone.",
    estimatedMinutes: 12,
    capstone: true,
  },
  {
    id: "C1-D4-O1-HYPERVISOR-LAB",
    slug: "hypervisor-match",
    title: "Virtualization stack matching lab",
    kind: "network",
    objectiveIds: ["C1-D4-O1"],
    conceptIds: [
      "C1-D4-O1-TYPE1",
      "C1-D4-O1-TYPE2",
      "C1-D4-O1-VDI",
      "C1-D4-O1-CONTAINER",
    ],
    component: "HypervisorMatchLab",
    description:
      "Match Type 1, Type 2, VDI, and containers to datacenter, laptop-lab, clinic, and microservice tickets; leave SaaS mail and thick-client reimage unused.",
    solution:
      "Type 1 bare-metal for datacenter consolidation. Type 2 hosted on a tech laptop. VDI keeps ward desktops central. Containers share a kernel for dense microservices. SaaS email and reimaging thick clients are not virtualization stack answers.",
    estimatedMinutes: 12,
    capstone: true,
  },
  {
    id: "C1-D5-O4-MOBILE-HW-LAB",
    slug: "mobile-hardware-ts",
    title: "Mobile hardware troubleshooting lab",
    kind: "hardware",
    objectiveIds: ["C1-D5-O4"],
    conceptIds: [
      "C1-D5-O4-SWELL",
      "C1-D5-O4-DIGITIZER",
      "C1-D5-O4-LIQUID",
    ],
    component: "MobileHardwareTsLab",
    description:
      "Match swollen-battery, digitizer, liquid, and charge-path FIRST actions; leave factory-reset-first and buy-a-phone unused.",
    solution:
      "Swollen pack: power off, do not charge, OEM replace. Digitizer when image is fine. Liquid: power off, do not charge. Charge issues: known-good cable/port before battery. Factory reset and buying a phone are not FIRST on unsafe hardware.",
    estimatedMinutes: 12,
    capstone: true,
  },
  {
    id: "C2-D3-O3-COMPROMISE-LAB",
    slug: "compromised-phone",
    title: "Compromised phone triage lab",
    kind: "security",
    objectiveIds: ["C2-D3-O3"],
    conceptIds: [
      "C2-D3-O3-JAILBREAK",
      "C2-D3-O3-SPOOFAPP",
      "C2-D3-O3-DATAUSAGE",
    ],
    component: "CompromisedPhoneLab",
    description:
      "Match sideload, jailbreak/root, data-spike, and overlay scareware tickets to FIRST software actions; leave battery-swap and raise-cap unused.",
    solution:
      "Sideload → remove unofficial apps. Jailbreak → isolate and wipe to stock. Data spike → sort by app. Scareware overlay → revoke overlay/uninstall. Do not swap batteries or raise the carrier cap as FIRST.",
    estimatedMinutes: 12,
    capstone: true,
  },
  {
    id: "C1-D1-O2-ACCESSORY-LAB",
    slug: "mobile-accessories",
    title: "Mobile accessories matching lab",
    kind: "hardware",
    objectiveIds: ["C1-D1-O2"],
    conceptIds: [
      "C1-D1-O2-NFC",
      "C1-D1-O2-BT",
      "C1-D1-O2-DOCK",
      "C1-D1-O2-REPLICATOR",
    ],
    component: "MobileAccessoriesLab",
    description:
      "Match NFC tap, Thunderbolt dock, port replicator, and Bluetooth headset tickets; leave WLAN-for-pen and Lightning-on-Android unused.",
    solution:
      "NFC for short-range badge taps. Thunderbolt/USB-C dock for charge + displays + Ethernet. Port replicator multiplies ports without PD. Headset silence is profile/default device. WLAN does not fix pen offset; Lightning is not for USB-C Android.",
    estimatedMinutes: 12,
    capstone: true,
  },
  {
    id: "C1-D2-O4-SERVICES-LAB",
    slug: "network-services",
    title: "DNS DHCP VLAN VPN matching lab",
    kind: "network",
    objectiveIds: ["C1-D2-O4"],
    conceptIds: [
      "C1-D2-O4-DNSREC",
      "C1-D2-O4-DHCPPOOL",
      "C1-D2-O4-VLAN",
      "C1-D2-O4-VPN",
    ],
    component: "NetworkServicesLab",
    description:
      "Match DNS A/AAAA, DHCP reservation, VLAN guest isolation, and VPN remote access; leave port-forward-as-VPN and mask-as-VLAN unused.",
    solution:
      "Fix names with DNS A/AAAA. Sticky printer IPs use DHCP reservation. Guests get a separate VLAN. Hotel workers use client VPN. Port-forward is not a corp VPN; changing one PC mask is not a VLAN.",
    estimatedMinutes: 12,
    capstone: true,
  },
  {
    id: "C2-D1-O1-OSTYPES-LAB",
    slug: "os-types",
    title: "OS types and filesystems matching lab",
    kind: "os",
    objectiveIds: ["C2-D1-O1"],
    conceptIds: [
      "C2-D1-O1-WIN",
      "C2-D1-O1-LINUX",
      "C2-D1-O1-MAC",
      "C2-D1-O1-CHROMEOS",
      "C2-D1-O1-FS",
      "C2-D1-O1-EOL",
    ],
    component: "OsTypesLab",
    description:
      "Match Windows domain, Linux/ext4, ChromeOS kiosk, and macOS/APFS tickets; leave NTFS-USB-for-Mac and Win7-EOL unused.",
    solution:
      "Windows for domain GPO. Linux with ext4/XFS for the forge VM. ChromeOS for managed lobby kiosks. macOS with APFS for creative Macs. Shared flash for Mac+Windows wants exFAT; EOL Win7 is unsupported even if it boots.",
    estimatedMinutes: 12,
    capstone: true,
  },
  {
    id: "C2-D4-O4-SAFETY-LAB",
    slug: "safety-procedures",
    title: "Safety procedures matching lab",
    kind: "ticket",
    objectiveIds: ["C2-D4-O4"],
    conceptIds: [
      "C2-D4-O4-ESD",
      "C2-D4-O4-GROUND",
      "C2-D4-O4-PPE",
      "C2-D4-O4-LIFT",
    ],
    component: "SafetyProceduresLab",
    description:
      "Match ESD, disconnect-power, PPE, and team-lift tickets; leave open-PSU and Class-A-on-electrical unused.",
    solution:
      "ESD strap+mat before boards. Unplug/drain before opening a case. Goggles/mask for toner dust. Team-lift heavy UPS gear. Never service inside a PSU; electrical fires are not Class A water jobs.",
    estimatedMinutes: 12,
    capstone: true,
  },

  {
    id: "C1-D1-O3-MDM-LAB",
    slug: "mobile-mdm",
    title: "Mobile MDM and cellular matching lab",
    kind: "hardware",
    objectiveIds: ["C1-D1-O3"],
    conceptIds: [
      "C1-D1-O3-ESIM",
      "C1-D1-O3-MDM",
      "C1-D1-O3-BYOD",
      "C1-D1-O3-DATACAP",
    ],
    component: "MobileMdmLab",
    description:
      "Match eSIM/cellular identity, MDM enroll, BYOD selective wipe, and data-cap tickets; leave full-wipe-BYOD and WLAN-for-GPS unused.",
    solution:
      "eSIM/SIM for missing cellular. MDM enroll for corp compliance. Selective wipe for BYOD return. Data meter / Wi-Fi sync for caps. Do not full-wipe personal BYOD or swap WLAN for GPS faults.",
    estimatedMinutes: 12,
    capstone: true,
  },
  {
    id: "C1-D2-O8-TOOLS-LAB",
    slug: "network-tools",
    title: "Networking tools matching lab",
    kind: "network",
    objectiveIds: ["C1-D2-O8"],
    conceptIds: [
      "C1-D2-O8-CRIMPER",
      "C1-D2-O8-PUNCHDOWN",
      "C1-D2-O8-TONER",
      "C1-D2-O8-ANALYZER",
    ],
    component: "NetworkToolsLab",
    description:
      "Match crimper, punchdown, toner, and Wi-Fi analyzer tickets; leave loopback-for-Wi-Fi and tap-for-crimp unused.",
    solution:
      "Crimper terminates patch plugs. Punchdown lands horizontal cable on IDC. Toner finds unlabeled drops. Wi-Fi analyzer for channel overlap. Loopback is not RF planning; a tap does not terminate cable.",
    estimatedMinutes: 12,
    capstone: true,
  },
  {
    id: "C2-D2-O3-WIFISEC-LAB",
    slug: "wireless-security",
    title: "Wireless security protocols matching lab",
    kind: "security",
    objectiveIds: ["C2-D2-O3"],
    conceptIds: [
      "C2-D2-O3-WPA3",
      "C2-D2-O3-WPA2",
      "C2-D2-O3-AES",
      "C2-D2-O3-RADIUS",
      "C2-D2-O3-KERBEROS",
    ],
    component: "WirelessSecurityLab",
    description:
      "Match WPA3-Personal, Enterprise+RADIUS, AES-only, and Kerberos SSO; leave WEP/open and TKIP-for-speed unused.",
    solution:
      "WPA3-Personal (SAE) upgrades guest PSK. Enterprise+RADIUS for per-user corp Wi-Fi. AES-only — disable TKIP. Kerberos is domain SSO, not an AP passphrase. WEP/open and TKIP stay findings.",
    estimatedMinutes: 12,
    capstone: true,
  },
  {
    id: "C2-D4-O5-ENV-LAB",
    slug: "environment-controls",
    title: "Environmental and power controls matching lab",
    kind: "ticket",
    objectiveIds: ["C2-D4-O5"],
    conceptIds: [
      "C2-D4-O5-UPS",
      "C2-D4-O5-BROWNOUT",
      "C2-D4-O5-MSDS",
      "C2-D4-O5-HUMIDITY",
    ],
    component: "EnvironmentControlsLab",
    description:
      "Match UPS, surge suppressor, SDS disposal, and humidity/ESD tickets; leave daisy-chain and water-on-lithium unused.",
    solution:
      "UPS for brownout/blackout ride-through. Surge when no battery is needed. SDS for toner/battery disposal. Humidity/vents for ESD/dust. Never daisy-chain UPS/strips or water lithium like Class A trash.",
    estimatedMinutes: 12,
    capstone: true,
  },
];
